### ISSUE TITLE
很棒一些期许

### ISSUE THREAD

**Issue by hkx8037** [gurecn/YuyanIme#101]
非常棒了，一名普通九宫格用户的一些期许。

手写这个是个人刚需，因为有时候往字典里面录入一些不认识的生字，手写就很派上用场。

侧边栏字符允许像讯飞自定义（因为有时候网上抢购或是其他，提前把有用信息自定义到侧边栏）会大大节省时间，这个侧边栏自定义功能和常用语个人觉得冲突。个人觉得侧边栏自定义功能优于常用语，因为你的字符后面是什么自定义只有你自己知道，其他人不知道相对隐私一点。

越来越好

**Comment by gurecn** [comment]
+ 手写功能预计本周五版本加入，已经开发完成了。
+ 侧边栏符号自定义功能当前最新版本已经支持了，您使用的是20241012.18版本吗？还是其他需求？

**Comment by 751496032** [comment]
> * 手写功能预计本周五版本加入，已经开发完成了。
> * 侧边栏符号自定义功能当前最新版本已经支持了，您使用的是20241012.18版本吗？还是其他需求？

![image](https://github.com/user-attachments/assets/65b4e7e8-43e3-4788-aab9-8345498a4a64)

你好，在原键盘上加了一个布局，发现布局关标处不会往上顶，是什么问题

**Comment by hkx8037** [comment]
> * 手写功能预计本周五版本加入，已经开发完成了。
> * 侧边栏符号自定义功能当前最新版本已经支持了，您使用的是20241012.18版本吗？还是其他需求？


https://github.com/user-attachments/assets/391aeef1-f04d-4f32-a285-b9d46e64af00

您好我使用的是20241012.18版本，期待周五有手写功能的版本发布，自定义符号录了个小视频，咱俩都没说错，自定义符号功能有需求，期待！！

**Comment by gurecn** [comment]
明白你的意思了，就是将侧边栏展示内容和输入内容分开，这个我列入后续计划。

**Comment by gurecn** [comment]
[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241206.20)已增加该功能，请下载体验。
