### ISSUE TITLE
全键盘一些建议？

### ISSUE THREAD

**Issue by hxchtiewei** [gurecn/YuyanIme#102]
用了有一段时间，非常感谢能开发这么好的输入法。
因为主要使用全键盘，所以想提些需求，您随意看看能否实现~~
1、全键盘的“数字行”按键能否大一点，和字母按键一样大。现在的大小按起来有点费劲。
2、按键上划输入能否也有气泡提示。
3、全键盘的中英文切换按钮能否隐藏，中英文切换启用“上划空格键”，这样“逗号按键”就可以移到原来中英文按键位置。这样布局上“空格”就处于正中间位置了。

**Comment by gurecn** [comment]
感谢您的建议。数字行按键大小在[新版本v20241018.21](https://github.com/gurecn/YuyanIme/releases/tag/v20241018.21)已经优化。
另外两个问题我有参考了一下体验比较好的微信输入法，发现当前实现方式也和雨燕输入法一样，后续有时间了我调研更多一些输入法，取长补短，提雨燕输入的体验。
