### ISSUE TITLE
bug反馈：退出王者突然不能打字了

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#103]
游戏预选英雄过程中我有打字和移动悬浮键盘，最后一次打字没打完就载入游戏了，之后退出游戏后就不能打字了，我尝试上滑发现可以输入，然后切换数字键盘也可以输入数字，再切回中文键盘又恢复正常了，以前用旧版本也遇到过这个bug，我以为覆盖安装导致的，但这次更新新版本后我有清除数据，以下是动图
![Video_20241015_113615_457.gif](https://github.com/user-attachments/assets/620bb1a3-058b-47e5-be5d-11aa6111caa7)

**Comment by swh922** [comment]
又遇到了奇怪的bug，字延后出来，打下一个字的时候，上一个字才冒出来，比如下面的视频，我打一句话“测试一下看看”，打“试”的时候出来“测”，打“一”的时候出来“试”，后面以此类推，我切换9键又切回乱序17才恢复正常
https://github.com/user-attachments/assets/c7be68db-371d-497d-bf1d-adc0b71c92e0

**Comment by gurecn** [comment]
收到，我复现一下相关问题，争取尽快修复。

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
