### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by parauni** [gurecn/YuyanIme#105]
请问能否出一个编辑栏？很多输入法都有这个功能,感觉很方便，没有这个挺不习惯
如图所示
小企鹅的
![Screenshot_2024-10-17-20-58-17-006_com microsoft emmx-edit](https://github.com/user-attachments/assets/aaf2d7b7-66d9-47f5-aa62-e1225e118e14)
gboard的
![Screenshot_2024-10-17-20-59-31-977_com microsoft emmx-edit](https://github.com/user-attachments/assets/ceb1517f-48cb-4f33-ba52-fa71a6016d40)

**Comment by gurecn** [comment]
编辑键盘已经在规划了，请关注后续版本发布情况。
