### ISSUE TITLE
横屏无法关闭悬浮键盘

### ISSUE THREAD

**Issue by Shinnosuke-5** [gurecn/YuyanIme#106]
横屏关不了悬浮键盘，重新安装也不行看，设置里面也关了悬浮键盘

https://github.com/user-attachments/assets/f9d21124-b3fe-43a3-819a-ded890fcc4e0

**Comment by gurecn** [comment]
当前横屏分栏键盘尚且开发完成，横屏时锁定悬浮键盘，后续待横屏分栏完成后会取消该限制。
