### ISSUE TITLE
没有笔画输入

### ISSUE THREAD

**Issue by 183868hlj** [gurecn/YuyanIme#109]
没有笔画输入

**Comment by gurecn** [comment]
新版本已增加笔画键盘，请下载尝试。

**Comment by cjx-2020** [comment]
> 新版本已增加笔画键盘，请下载尝试。

新版本无法切换至笔画键盘

<img width="2504" height="1460" alt="Image" src="https://github.com/user-attachments/assets/0bf68b10-9a3b-4c71-946b-7cee0a7bd1e7" />
