### ISSUE TITLE
这输入法bug有点多

### ISSUE THREAD

**Issue by xiechangan123** [gurecn/YuyanIme#110]
覆盖安装，版本2021.10.18
1、无法把拼音清屏，反而把输入框里面的清了，有视频

https://github.com/user-attachments/assets/49f7e240-01cf-4f25-9f4a-7499f1af1704
2、到现在都没有模糊音，完全可以把模具音限制在全键上，九宫格不允许模糊音，江南人90%都分不清l n in ing；
3、手写是可有可无锦上添花的东西，还是第三方外挂形式，能玩你这输入法的都是非主流大学生，有几个还用手写？目前不是急需的
希望作者拎清主次和核心功能而不是全能输入法，还有就是修bug

**Comment by gurecn** [comment]
收到您的反馈。
+ 无法清屏的问题按照您的输入已复现，下个版本会修复。
+ 模糊音功能已经列入开发计划，预计最近几个版本就能加入。
雨燕输入法的缺陷我会优先修复，尽量完善大家的输入体验，感谢您的反馈与支持。

**Comment by xiechangan123** [comment]
> 无法把拼音清屏的问题新版本v2024102113已修复，邀请您安装体验。

确实没问题啦，就等模糊音了。关贴
