### ISSUE TITLE
九宫格输入过程中误触上划

### ISSUE THREAD

**Issue by flyear8** [gurecn/YuyanIme#114]
九宫格拼音输入的时候，打字速度比较快的情况下，有比较大的概率误触上划功能，变成上划输出数字。导致正常的拼音汉字输出经常中断，要中断打字先删除误触的内容，打字效率大大降低，体验非常不好。
目前只能先把上划功能关闭，希望能把点按和上划两个动作的区分度调高一点，避免误触。

**Comment by gurecn** [comment]
新版本已增加上划输入灵敏度控制，您在上划功能关闭按钮旁可以看到，请调整灵敏度后尝试。
