### ISSUE TITLE
不是说不联网吗

### ISSUE THREAD

**Issue by az4399** [gurecn/YuyanIme#115]
`不联网、不获取任何权限，更安全。`

为啥几天没看更新居然获取联网权限了

联网就很难受，我感觉我是这种宁愿牺牲一丢丢便利，也不要联网的

请问后续是否会继续获取联网权限呢？

**Comment by gurecn** [comment]
抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。
我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。
项目说明我会同步更新。

**Comment by swh922** [comment]
> 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。
> 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。
> 项目说明我会同步更新。

我之前用讯飞和百度的时候，都是禁止连网使用的，手写都可以正常用，希望语燕手写以后也可以做到无网使用，我相信语燕的大部分用户应该都是奔着简洁和不连网来的，这款输入法毕竟主打的是隐私保护

**Comment by VeleSila** [comment]
> 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。 项目说明我会同步更新。

我的建议是在开始手写的时候加一个弹窗提示，以避免分版本。目前只有你一个人在开发，不要给自己增加后续维护压力。

**Comment by VeleSila** [comment]
> > 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。
> > 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。
> > 项目说明我会同步更新。
> 
> 我之前用讯飞和百度的时候，都是禁止连网使用的，手写都可以正常用，希望语燕手写以后也可以做到无网使用，我相信语燕的大部分用户应该都是奔着简洁和不连网来的，这款输入法毕竟主打的是隐私保护

欢迎你给作者分享好的开源的手写识别项目。否则你要求一个个人开发者去加入私人公司才有人力财力去开发的功能并不现实。

**Comment by gurecn** [comment]
网络权限是普通权限。如果在代码中添加声明使用了应用就可使用网络，未声明的话就无法调用互联网。如果不区分版本，应用一旦添加声明，理论上就有使用互联网的能力了，弹窗只是一种展示，可信度不强。
手写功能确实不是一个人可以开发的，当前项目在成本的考虑，使用了汉王增值服务在线识别服务，后续我根据情况看是否可以切换到离线识别。
感谢你们的建议与支持。

**Comment by az4399** [comment]
> 网络权限是普通权限。如果应用在代码中添加网络权限声明，无需用户确认即可使用网络；未添加声明的话就无法调用互联网。如果不区分版本，应用一旦添加声明，理论上就有使用互联网的能力了，弹窗只是一种展示，可信度不强。 手写功能确实不是一个人可以开发的，当前项目在成本的考虑，使用了汉王增值服务在线识别服务，后续我根据情况看是否可以切换到离线识别。 感谢你们的建议与支持。

还是希望别获取联网权限，如果手写必须是在线的，而且也有人需要手写（年轻人基本不会用手写），那肯定得分离线、在线版本

**Comment by az4399** [comment]
> > 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。 项目说明我会同步更新。
> 
> 我的建议是在开始手写的时候加一个弹窗提示，以避免分版本。目前只有你一个人在开发，不要给自己增加后续维护压力。

弹窗没有任何意义，保护隐私就是绝对不联网，要不然直接用现成的大厂输入法关闭联网权限不好吗，还更好用，语燕相比大厂的输入法暂时没那么好用，但为什么继续用，不就是看重不联网吗

**Comment by az4399** [comment]
> > > 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。
> > > 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。
> > > 项目说明我会同步更新。
> > 
> > 
> > 我之前用讯飞和百度的时候，都是禁止连网使用的，手写都可以正常用，希望语燕手写以后也可以做到无网使用，我相信语燕的大部分用户应该都是奔着简洁和不连网来的，这款输入法毕竟主打的是隐私保护
> 
> 欢迎你给作者分享好的开源的手写识别项目。否则你要求一个个人开发者去加入私人公司才有人力财力去开发的功能并不现实。

不是说要求必须做到，因为毕竟开源项目，现在也确实是在无偿发电，只是提建议，作者大佬也可以不接受，我们换一个输入法就行了，来去自由嘛

**Comment by VeleSila** [comment]
> > > 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。 项目说明我会同步更新。
> > 
> > 
> > 我的建议是在开始手写的时候加一个弹窗提示，以避免分版本。目前只有你一个人在开发，不要给自己增加后续维护压力。
> 
> 弹窗没有任何意义，保护隐私就是绝对不联网，要不然直接用现成的大厂输入法关闭联网权限不好吗，还更好用，语燕相比大厂的输入法暂时没那么好用，但为什么继续用，不就是看重不联网吗

App到底是否有联网都是可以看到数据的。弹窗前你看不到数据使用记录即可。不是系统自带app，又无法作弊，app 本身也是开源，你再怕一点完全可以自己编译。
当然，作者本身似乎也明白中文环境下用户甚至对来源app的信任度都有问题。所以作者已经决定采取更复杂的措施了。

**Comment by az4399** [comment]
> > > > 抱歉，当前手写功能需要使用网络识别，这确实和最初规划不同。 我计划下个版本分两个版本推出，一个无需权限、不含手写功能，一个需要网络权限、包含手写功能。 项目说明我会同步更新。
> > > 
> > > 
> > > 我的建议是在开始手写的时候加一个弹窗提示，以避免分版本。目前只有你一个人在开发，不要给自己增加后续维护压力。
> > 
> > 
> > 弹窗没有任何意义，保护隐私就是绝对不联网，要不然直接用现成的大厂输入法关闭联网权限不好吗，还更好用，语燕相比大厂的输入法暂时没那么好用，但为什么继续用，不就是看重不联网吗
> 
> App到底是否有联网都是可以看到数据的。弹窗前你看不到数据使用记录即可。不是系统自带app，又无法作弊，app 本身也是开源，你再怕一点完全可以自己编译。 当然，作者本身似乎也明白中文环境下用户甚至对开源app的信任度都有问题。所以作者已经决定采取更复杂的措施了。

我觉得没谁会每天关注数据使用量，不管是不是自己编译，不联网啥事都没有，联网就是增加不确定性，谁都不想赌

**Comment by gurecn** [comment]
最新版本已区分离线、在线版本，该问题不用纠结了。感谢大家的支持和建议。
