### ISSUE TITLE
拼音全键（非双拼键盘）也有双拼助记，无用望去掉

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#117]
![Screenshot_20241022-074140_Alpha Launcher.png](https://github.com/user-attachments/assets/1a1fb3b0-df6e-4b7e-b4fb-48ebc0eb90f4)

**Comment by gurecn** [comment]
收到反馈，下个版本修复该问题。

**Comment by gurecn** [comment]
该问题在新版本已经修复，请下载体验。
