### ISSUE TITLE
麻烦完善下scrcpy模式下的键盘中英文输入

### ISSUE THREAD

**Issue by crazyn2** [gurecn/YuyanIme#118]
scrcpy模式下的键盘中英文输入，目前有很多不完善的地方，比如中文打字是可以的，但是拼音和中文会一起输入。按shift键无法切换中英文，英文输入会把键盘输入和输入法输入都输入了一遍

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)
