### ISSUE TITLE
能不能增加调整长按调整时间?

### ISSUE THREAD

**Issue by zhl111** [gurecn/YuyanIme#12]
下午使用了许久，整体感觉都非常好，唯一不顺畅的就是标点符号的输入
1. 习惯了企鹅输入法调整的短延时长按功能,现在输入标点符号感觉好慢
2. 这能增加单独的标点符号与emoji切换的功能?
3. 这输入法上面空了很大一块,可否利用一下?其实倒也无所谓，就是标点符号的输入感觉麻烦好多
4. 按键音量我设为1%，仍然声音很大，似乎不能调小？
![Screenshot_20240817_154754_Kiwi Browser](https://github.com/user-attachments/assets/d2772216-2ca0-4fe9-ac87-20d814f8366e)

**Comment by gurecn** [comment]
感谢支持，我关注一下这几个问题，有更新我及时通知

**Comment by gurecn** [comment]
1. 习惯了企鹅输入法调整的短延时长按功能,现在输入标点符号感觉好慢
> 是否指触发长按的延时？

2. 这能增加单独的标点符号与emoji切换的功能?
> 这个没太命名，能详细描述或者截图看一下吗？

3. 这输入法上面空了很大一块,可否利用一下?其实倒也无所谓，就是标点符号的输入感觉麻烦好多
> 上面那一块有两栏：上面显示第一个候选词的拼音；下面显示候选词。没有空很大吧？标点符号麻烦是指下面[您补充的描述](https://github.com/gurecn/YuyanIme/issues/12#issuecomment-2294984536)吗？在标点符号界面时，候选词栏显示的是最近使用符号，没有最近符号时显示常用符号。APG有重复我检查一下，包括半角全角感谢指出，后续我优化一下，但是可以定下个版本能上。又更新我会在这里基石同步。

4. 按键音量我设为1%，仍然声音很大，似乎不能调小？
> 什么机型？能否验证一下其他输入法是否正常？我小米手机测试是没有问题的，您什么机型我想办法试试。

感谢您的体验与反馈。

**Comment by gurecn** [comment]
我的手机是三星s23u，我设置1%和100%时的按键音都一样，即使我把手机静音
我用三星自带输入法，它的声音默认很小声，不可调。用小企鹅，声音与雨燕一样大声，即使静音
或许是三星手机不可调？但如果雨燕也是默认小声音的话，不可调也问题不大
> 雨燕输入法和小企鹅一样，当音量滑到头时，不是最小音量，而是系统默认音量。您尝试将滑块滑到5%或者不是默认音量的其他位置尝试一样，音量有变化吗？

部分功能在最新的[v4.3.3版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.3.3)已经优化，邀请您体验。

**Comment by gurecn** [comment]
感谢您的反馈，期待您继续支持。
音量的话，我找了一个三星s10+ （`ONE UI 3.0, Android 11`），没有复现您的问题。暂时没办法复现了
