### ISSUE TITLE
九宫格拼音等bug&建议

### ISSUE THREAD

**Issue by gmere** [gurecn/YuyanIme#120]
bug
1.   241021版本九宫格"pqrs"键位开头的拼音组合，选中以"p"开头的拼音后删除一个字母整个跳转以"mno"键位开头的拼音;
2.   下拉候选词删除键遮挡部分字词;
3.    第一个候选字有时难以选中，是否可以减少候选词以增加字间距。

建议
      某些场景下，比如FDM(一款下载器)重命名栏无法调出中文键盘，Gborad等输入法也是如此，唯有小企鹅输入法可以。

**Comment by gurecn** [comment]
FDM(一款下载器)重命名栏无法调出中文键盘  这个能截一下是哪个界面吗？

**Comment by gurecn** [comment]
1.九宫格"pqrs"键位开头的拼音组合，选中以"p"开头的拼音后删除一个字母整个跳转以"mno"键位开头的拼音
> 该问题已修复，会在下个版本发布
2、3问题最新版本已修复，请下载体验。
