### ISSUE TITLE
空格键滑动控制光标过于灵敏

### ISSUE THREAD

**Issue by monkeyotg** [gurecn/YuyanIme#122]
要一个字符一个字符移动光标时太灵敏了。拇指要肌肉高度紧张，精确控制滑动幅度才能做到准确定位，失去了这个功能的意义了。

**Comment by gurecn** [comment]
请问你们使用的是最新版本吗？麻烦使用最新版本测试一下，光标滑动过快的问题在之前版本已经修复了，现在基本上能控制精确位置了才对。

**Comment by monkeyotg** [comment]
最新版试了一下，这个问题解决了

**Comment by monkeyotg** [comment]
最新版试了一下，这个问题解决了

**Comment by monkeyotg** [comment]
不能 Close Issue?

**Comment by gurecn** [comment]
OK，好的，感谢使用与支持。
