### ISSUE TITLE
prism.bin文件如何制作

### ISSUE THREAD

**Issue by chougousui** [gurecn/YuyanIme#126]
我想引入格道17(类似乱17),但发现除了schema.yaml文件,还需要准备一个二进制的prism.bin文件,这个文件是怎么产生的啊.需要借助什么外部工具或环境吗

我在archlinux上尝试了一下(安装了 librime)

准备了这些文件
- essay.txt(来自/usr/share/rime-data/essay.tx)
- pinyin.dict.yaml(来自/usr/share/rime-data/luna_pinyin.dict.yaml 并修改了一些内容)
- default.yaml (来自yuyansdk/src/main/assets/rime/build/default.yml)
- double_pinyin_gd17.schema.yaml

然后运行
`rime_deployer --compile double_pinyin_gd17.schema.yaml`
结果虽然出现了 build/double_pinyin_gd17.prism.bin 这个文件,但最终应用跑起来后觉得按键错位,比如视觉上是D,但实际拼写出来的,更像是按下了C.视觉是M,实际上更像L.

使用同样方法处理原有的 double_pinyin_ls17.schema.yaml,生成的bin文件使用起来也会感觉有错位

**Comment by gurecn** [comment]
语言输入法内置编译好的rime方案，不支持自定义和重新部署。自己编译的话，可以使用鼠须管、中州韵、小狼毫部署方案，部署后会生成对应的文件，但不确定您编译的方案能否生效哈

**Comment by chougousui** [comment]
是的,看目前源码内容,不支持重新部署. `yuyansdk/src/main/assets/rime/build`文件夹中存放的是已经编译好的内容了.我想添加一个类似乱序17的格道17布局,但在prism.bin的文件准备上卡住了,其他键盘绘制和显示方面没有太大问题,作者方面分享一下编译前的一些schema文件吗?

目前现状是,显示按下的按键问题不大,但实际上拼写出来的不对,比如目前按下(Ch, i),实际上按下的并不等同于看到的内容
![Screenshot_20241116_190558_GNotes_1](https://github.com/user-attachments/assets/01ff1347-f851-414b-88c8-17d2f94c0bdd)

**Comment by chougousui** [comment]
作者方便分享一下rime部署前的一些配置文件吗?我真的很想添加新的键盘布局,现在就是卡在了rime的编译部分,我自己试过好多办法都不行

**Comment by gurecn** [comment]
部署前的配置就是雾凇拼音方案+白霜词库啊，不过因为代码兼容键盘问题，可能部分配置有稍许区别，后续我将雨燕使用的方案也创建个项目传上来吧

**Comment by mtzMobileDev** [comment]
作者是否能分享下如何将白霜词库内置进来的操作流程，脚本之类的，这样我可以通过扩充白霜的词组实现自定义词库的需求
