### ISSUE TITLE
增加"重新部署"按键或者功能

### ISSUE THREAD

**Issue by parauni** [gurecn/YuyanIme#129]
输入法基于rime,有些地方可以自定义。希望可以增加“重新部署”功能，否则我改完配置后无法生效。目前我不知道如何触发部署，删掉build文件夹和重新安装都不行

**Comment by gurecn** [comment]
语言输入法规划不支持自定义方案和重新部署，雨燕输入法的目的是为了推出一个上手简单、体验良好的rime输入法，若是有自定义需求，建议使用同文或小企鹅输入法哈

**Comment by widcardw** [comment]
感觉可以把这个 issue 的标题更改一下叫“不支持自定义方案的说明”（或者 pin 一下），避免已经做了同文自定义方案的用户来问为啥没有“自定义方案”和“重新部署”。

（我是简拼用户，被 rime-frost 中 went、Laos、bus 这类不应该出现在第一个词的英文单词折磨了，每次都是通过更改 `reduce_english_filter`, `mode='all'`, `idx=4` 来实现的）
