### ISSUE TITLE
希望适配线性马达震动

### ISSUE THREAD

**Issue by crumbledwall** [gurecn/YuyanIme#131]
现在的输入按键震动是老式的震动方式，选择系统震动强度时，没有适配线性马达的自然震动，希望后续可以增加这个适配

**Comment by tsaiajie** [comment]
震动方式还有分这个啊 我都不知道 问问有什么输入法适配了线性马达的自然震动 我去看看效果是怎么样子的

**Comment by yongdaimei** [comment]
我就是因为没有不用的，提了作者也不回复

**Comment by gurecn** [comment]
收到该反馈，我会调研相关功能，在后续版本修复。感谢你们的支持

**Comment by gurecn** [comment]
新版本在键盘效果-触感强度-选择系统触感效果时，使用系统支持的线性马达，请下载体验。

**Comment by crumbledwall** [comment]
感谢！现在体验很不错，作者辛苦了
