### ISSUE TITLE
支持自定义方案吗？

### ISSUE THREAD

**Issue by Attiv** [gurecn/YuyanIme#134]
比如 虎码，星猫键道这些，可以手动导入吗

**Comment by silent3713** [comment]
暂时好像不支持，我也想导入自己的码表。

**Comment by gurecn** [comment]
语言输入法规划不支持自定义方案和重新部署，雨燕输入法的目的是为了推出一个上手简单、体验良好的rime输入法，若是有自定义需求，建议使用同文或小企鹅输入法哈

**Comment by Attiv** [comment]
> 语言输入法规划不支持自定义方案和重新部署，雨燕输入法的目的是为了推出一个上手简单、体验良好的rime输入法，若是有自定义需求，建议使用同文或小企鹅输入法哈

请问如果想自己加的话应该怎么做？我把sdk 里 build/里的小鹤双拼换成我想换的方案后是不生效的，还需要改哪里？

**Comment by gurecn** [comment]
雨燕输入法键盘是内置的，和其他输入法键值不同，所以不能直接替换。
