### ISSUE TITLE
建议效仿主流输入法增加双括号、双引号等，提高输入效率

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#137]
如图
![IMG_20241106_090648.jpg](https://github.com/user-attachments/assets/c47512a2-10b4-43a4-9535-1f73cd2c3090)

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
