### ISSUE TITLE
缺少“粄”字

### ISSUE THREAD

**Issue by ggb6070** [gurecn/YuyanIme#138]
如题

**Comment by swh922** [comment]
拼音打不出来，手写可以
![Screenshot_20241107-105022_GitHub.png](https://github.com/user-attachments/assets/13c41bb0-af70-49ce-8380-d29a8275d3fb)

**Comment by gurecn** [comment]
[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)优化词库，邀请大家使用新版本测试，期待你们的反馈。
