### ISSUE TITLE
[bug] 剪贴板问题

### ISSUE THREAD

**Issue by zhl111** [gurecn/YuyanIme#14]
现在这个剪贴板的界面很奇怪，我无论复制什么，显示的都是这上面的内容，我点x消除后再去复制，这条内容又重复出现了…也就是说无法复制新的内容到剪贴板

再试，出现错误提示的弹窗:需要清除缓存…清完缓存，这图片上的剪贴板最上面的内容还在，最后，我把剪贴板内容一条条全部清空后,正常了

是不是可以增加一个一键清除剪贴板的功能

**Comment by gurecn** [comment]
您的意思是，您复制 `您好1` 后，弹出键盘直接在候选词栏显示 `您好1` .再复制 `您好2` 后，弹出键盘仍然时，显示的仍然是 `您好1`?

**Comment by gurecn** [comment]
好的，我尝试复现一下。您说的清除全部缓存功能我也规划进去。

**Comment by gurecn** [comment]
该功能在最新的[v4.3.3版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.3.3)已经优化，邀请您体验。
