### ISSUE TITLE
关于删除键或者回退键长按触发的选单的疑问。

### ISSUE THREAD

**Issue by RejectVanity** [gurecn/YuyanIme#142]
长按删除键或者回退键会弹出三个选项，很疑惑他们的用途。

而且我也希望能给出关闭它的选项，因为它很影响我长按操作。

**Comment by gurecn** [comment]
三个菜单从左向右分别是恢复清空内容、清空输入框、长按删除。若您就是长按删除的话，按住删除键不要向左滑动即可。
后续我在长按菜单中添加文字描述。
