### ISSUE TITLE
在微信群里输入@，怎么拉起群里的的群员明细？

### ISSUE THREAD

**Issue by zhyqieqie** [gurecn/YuyanIme#144]
我想要在微信群里输入内容的时候，输入@能拉起群成员，这样能@相应的人。你们怎么做到的？

**Comment by 2LC16** [comment]
> 我想要在微信群里输入内容的时候，输入@能拉起群成员，这样能@相应的人。你们怎么做到的？

微信的锅，不是输入法的问题。一般是微信识别到输入框内输入了@符号就自动弹出列表
