### ISSUE TITLE
9键按键卡顿

### ISSUE THREAD

**Issue by laurenafolk** [gurecn/YuyanIme#149]
最近两三个版本，按下一个键，大约0.5秒按键阴影才消失或者说键才弹起来，不知道作者或者大家有这个问题没有

**Comment by gurecn** [comment]
哪个机型和系统？可能和词库大小有关。

**Comment by gurecn** [comment]
好的，我找机型测试一下。词库是默认的，无法修改。上个版本是更新了最新词库，有可能词库扩充导致了卡顿。

**Comment by Suchbear** [comment]
> 好的，我找机型测试一下。词库是默认的，无法修改。上个版本是更新了最新词库，有可能词库扩充导致了卡顿。

我用模拟器测试了就没问题，自己真机试就有问题，日志跑了一下是processRimeKey方法耗时长，看了一下其他开源也有todo说改异步的，但是没见真有人改，神奇的是在Rime下的processKey里return processRimeKey(keycode, mask)前打断点，直到输入法因为长期没有返回而崩溃，然后再拉起输入法竟然不卡了，但是关掉debug就寄，再拉起还是会卡，也不知道什么原理，而且我多次测试这是必现的，小米10pro android11

**Comment by 2LC16** [comment]
卡顿➕1，非常的奇怪🤔

**Comment by laurenafolk** [comment]
> > 好的，我找机型测试一下。词库是默认的，无法修改。上个版本是更新了最新词库，有可能词库扩充导致了卡顿。
> 
> 我用模拟器测试了就没问题，自己真机试就有问题，日志跑了一下是processRimeKey方法耗时长，看了一下其他开源也有todo说改异步的，但是没见真有人改，神奇的是在Rime下的processKey里return processRimeKey(keycode, mask)前打断点，直到输入法因为长期没有返回而崩溃，然后再拉起输入法竟然不卡了，但是关掉debug就寄，再拉起还是会卡，也不知道什么原理，而且我多次测试这是必现的，小米10pro android11

太强了 希望作者能解决，因为太卡顿了 现在暂时用的gboard@gurecn

**Comment by gurecn** [comment]
[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)优化词库，邀请大家使用新版本测试，期待你们的反馈。

**Comment by Mo2ph1ne** [comment]
> [新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)优化词库，邀请大家使用新版本测试，期待你们的反馈。

刚安装的新版本还是卡顿

**Comment by gurecn** [comment]
能录个视频吗？

**Comment by Suchbear** [comment]
没问题了，大哥牛逼！

**Comment by Suchbear** [comment]
> > [新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)优化词库，邀请大家使用新版本测试，期待你们的反馈。
> 
> 刚安装的新版本还是卡顿

不行的看下是不是代码没拉全，sdk的代码要拉

**Comment by laurenafolk** [comment]
#177，勾选字词过多还是会卡顿，不过正常交流一般就打2 3个字，不存在卡顿，作者加油

**Comment by Mo2ph1ne** [comment]
> 能录个视频吗？

#177 和这个情况一样，候选词多的时候 ， 或者输入过快的时候就会卡死了
