### ISSUE TITLE
是否支持自定义短语？

### ISSUE THREAD

**Issue by chinagaofeng** [gurecn/YuyanIme#15]
类似于trime里的custom_phrase.txt

**Comment by gurecn** [comment]
感谢您的支持。当前雨燕输入法尚不支持自定义短语功能。

**Comment by gurecn** [comment]
自定义短语功能在新版本已经实现，期待您下载使用。

**Comment by chinagaofeng** [comment]
> 自定义短语功能在新版本已经实现，期待您下载使用。

收到，已更新，已使用。

请问：自定义短语，是只能在手机上手动编辑？还是可以通过电脑连接手机修改某个文件？前者太慢太费劲了，如果能电脑辅助编辑就好了

**Comment by gurecn** [comment]
当前仅支持手机编辑，不支持电脑辅助编辑功能。
