### ISSUE TITLE
v20241113.12版本打字卡顿

### ISSUE THREAD

**Issue by klaus2025** [gurecn/YuyanIme#150]
v20241021.13以及之前版本正常

**Comment by QQQQQQQQiu** [comment]
+1

**Comment by lw-zg** [comment]
+1，明显感知不跟手了

**Comment by klaus2025** [comment]
> 卡顿的问题请大家使用[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)测试一下，有问题请及时反馈。

我手机上新版本打字正常了，谢谢
