### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by M-Cosmosss** [gurecn/YuyanIme#152]
版本20241113.12
如图所示，该情况yan的候选词缺失很多，例如找不到“燕”![IMG_20241117_225635.jpg](https://github.com/user-attachments/assets/a04fa7bb-54b0-427e-858a-caf45a66659a)

**Comment by gurecn** [comment]
收到。排查出来了。下个版本修复该问题

**Comment by gurecn** [comment]
新版本已修复该问题，请下载使用，感谢您的反馈与建议。
