### ISSUE TITLE
x键长按没有出现＊号

### ISSUE THREAD

**Issue by zhl111** [gurecn/YuyanIme#154]
同时，希望优化一下常用标点符号，不常用的符号放在第二屏吧。

**Comment by gurecn** [comment]
x键长按不应该出现*才对吧？是哪款输入法长按x会显示*呢？

**Comment by gurecn** [comment]
收到，问题已复现了，我没有开数字行，没有发现这个问题，下个版本修复该问题。感谢您的反馈。

**Comment by gurecn** [comment]
该问题已修复，请下载新版本使用。感谢您的建议。
