### ISSUE TITLE
小红书中键盘无法收回

### ISSUE THREAD

**Issue by famous7928** [gurecn/YuyanIme#156]
故障如视频显示https://github.com/user-attachments/assets/df07f521-c8e2-4f44-84dc-cc376e6f80c6

**Comment by gurecn** [comment]
该问题已复现，会尽快修复。感谢反馈

**Comment by gurecn** [comment]
无法收回键盘的问题，请使用[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)验证，感谢您的使用。

**Comment by famous7928** [comment]
> 无法收回键盘的问题，请使用[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)验证，感谢您的使用。

非常感谢，请问有安排五笔输入的功能吗？

**Comment by gurecn** [comment]
已列入后续规划中了
