### ISSUE TITLE
长按输入的识别有点问题，还有输入慢半拍

### ISSUE THREAD

**Issue by 2LC16** [gurecn/YuyanIme#157]
9键如果打开了上滑输入符号的话，如果打字快了就会出现："一下子按几个键，最后按到的那个键输入的是长按后才有的符号"的情况
可复现。目前关了上滑输入才可以正常使用
望修复。
另外还有一个情况，在最新的版本中会出现慢半拍额情况，手已经松开半天了但是按键按下的那个阴影还在，以及下一个键的震动迟迟不出来。（退回到241012版本就没有这个问题）

**Comment by gurecn** [comment]
第一个问题是因为上划识别太灵敏了，可以到设置−主题−上划输入灵敏度−调整为难触发。
第二个问题应该是词库太大导致的，下个版本我会移除不常用的细胞词库，增加大字表，请在下个版本验证一下卡顿情况。

**Comment by 2LC16** [comment]
> 第一个问题是因为上划识别太灵敏了，可以到设置−主题−上划输入灵敏度−调整为难触发。 第二个问题应该是词库太大导致的，下个版本我会移除不常用的细胞词库，增加大字表，请在下个版本验证一下卡顿情况。

好的，不过目前我暂时使用的241012版本还没有添加上滑灵敏度设置，期待下一个版本更完美。
另外提个建议，个人词库的同步可以设置一个坚果云之类的webdav，让用户自己设置备份同步，还可以备份用户的配置。(如果有更好没有也无伤大雅，已经做的很好了)

**Comment by gurecn** [comment]
词库同步问题很多人反馈了，以后会增加的

**Comment by 2LC16** [comment]
> 词库同步问题很多人反馈了，以后会增加的

非常期待新功能，若是可以加入拼音双键（非双拼）的模式就好了

**Comment by 2LC16** [comment]
> 词库同步问题很多人反馈了，以后会增加的

反馈一个问题，无法打出‘ 咁 ’字。音gan第一声

**Comment by gurecn** [comment]
新版本增加大字表，会增加不常用字就可以了

**Comment by 2LC16** [comment]
> 新版本增加大字表，会增加不常用字就可以了

现在发现一个问题，在符号里面没有双引号，只有单引号‘’，只有在英文的符号表中才能找到双引号。不过我现在使用的是241012版本，会不会是版本太老的问题

**Comment by gurecn** [comment]
感谢反馈，确实有这个问题，我加一下。预计明天发布版本会同时修复符号这个问题。

**Comment by 2LC16** [comment]
> 感谢反馈，确实有这个问题，我加一下。预计明天发布版本会同时修复符号这个问题。

目前我已升级最新版本，确实已经不卡顿了。
### 但是我又发现了两个bug。
其一是全屏优化下左边的功能会与系统本身的收起键盘的按键相冲突，而且将左边的按键从切换输入法改变为无功能后，切换输入法的那个🌐样式的图标仍然存在
![IMG_20241129_193439](https://github.com/user-attachments/assets/c9b3dd9e-7c78-45d9-a509-7c44ef0d14dc)
但是不会触发切换输入法的功能。
其二是在微信的输入框输入字后，通过输入法的滑动移动光标功能将光标向左移动，光标在移动到最左边后会自动消失且需要再次点按输入框才能出现光标并输入（无光标时是无法输入内容到输入框的）。这个bug在其他应用的输入框不会出现，仅在微信出现。
补充一下，目前我使用的手机是真我gtneo3，系统为安卓14的realmeui5.0

**Comment by gurecn** [comment]
收到，第一个问题会在下个版本修复，按键冲突问题可以在键盘调节，抬高键盘高度或者先关闭全面屏优化功能。第二个问题是必现的吗？我在手机上没有复现。

**Comment by 2LC16** [comment]
> 收到，第一个问题会在下个版本修复，按键冲突问题可以在键盘调节，抬高键盘高度或者先关闭全面屏优化功能。第二个问题是必现的吗？我在手机上没有复现。

好的。第二个应该是我的微信的问题，刚刚用谷歌拼音试了一下也出现了
