### ISSUE TITLE
关于“手写”的问题？

### ISSUE THREAD

**Issue by jkqxl** [gurecn/YuyanIme#159]
能否将 本地、网络版，合二为一。
即，增加一个网络启动按钮，以便在某些时刻使用网络功能，

之所以这样设置，是因为在某些时刻，手写等功能是必需的，但在大多数时候存在感又不强，但也不可能就据此，同时安装本地+联网的两个软件，那就显得更麻烦了。

遵循必要、最小化权限，其实还要加上，可依据用户的需求来进行选择。

**Comment by swh922** [comment]
> 能否将 本地、网络版，合二为一。
> 即，增加一个网络启动按钮，以便在某些时刻使用网络功能，
> 
> 之所以这样设置，是因为在某些时刻，手写等功能是必需的，但在大多数时候存在感又不强，但也不可能就据此，同时安装本地+联网的两个软件，那就显得更麻烦了。
> 
> 遵循必要、最小化权限，其实还要加上，可依据用户的需求来进行选择。

对于在意隐私的人来说，要的就是没有联网权限，你加上开关，手写暂时不用把开关关了，但是软件的联网权限还在😅

**Comment by gurecn** [comment]
对的，添加开关相当于把生杀大权交给了开发者，如果开发者不遵守约定，仍然可以在你选择关闭时使用网络。当前区分安装包，离线版本直接不获取相应权限，即便想不遵守约定也不行。
如果您想要的是一个开关的话，我建议使用在线版本，在您不使用手写功能时，雨燕输入法是不会主动联网的。

**Comment by gurecn** [comment]
嗯嗯，明白您的意思。
联网权限属于系统普通权限，应用只要声明需要网络权限就可以使用网络连接，系统没有提供在应用声明了需要网络的情况下通过开关关闭的接口。
有些国内定制系统可通过手机管家来限制应用联网，但这不是安卓系统功能，不是所有手机都支持的，且操作起来稍显复杂。
