### ISSUE TITLE
屏幕边缘触摸不良，第一个候选字上屏困难

### ISSUE THREAD

**Issue by iminto** [gurecn/YuyanIme#16]
一加8是曲面屏手机。
使用最新版（截止20240820），每次打字如果结果是第一个，上屏就很难
需要多次点击才能上屏，复现概率接近100%，但是gboad没有这个问题。

有一个平面屏手机，但因安卓版本10太低无法安装未测试。

**Comment by gurecn** [comment]
每次打字如果结果是第一个，上屏就很难
需要多次点击才能上屏，复现概率接近100%，但是gboad没有这个问题。  
> 本周五版本我加大候选词点击区域，到时候麻烦您再试一下，

有一个平面屏手机，但因安卓版本10太低无法安装未测试。  
> 应该不是版本低的问题，我用红米 note7（安卓9）安装使用没问题。怀疑是架构问题，您方便提供一下软硬件详细信息吗？

**Comment by gurecn** [comment]
以上问题在最新的[v4.3.3版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.3.3)已经优化，邀请您体验，期待您的反馈。

**Comment by iminto** [comment]
已经解决了，但是有一个更严重的问题，我新开个issue反馈。

**Comment by gurecn** [comment]
感谢您的反馈，期待您继续支持。
