### ISSUE TITLE
可以优化一下UI设计吗?还有这个图标ICON问题

### ISSUE THREAD

**Issue by Qifull** [gurecn/YuyanIme#161]
1. 打开键盘输入的时候,这个ICON当作设置出来太突兀了.颜色也跟周围不匹配非常难看,之前那个小鸟的logo形象还挺好看.现在这个意义不明.我的建议是如果想把你的设计抽象化,想想你这个产品的传播程度怎么样,这样会吸引其他人吗?很多大公司都是先有名气之后才对自己的品牌形象抽象化.
2. 好的键盘设计可以学习一下Gboard和小企鹅输入法,这两个的观感至少非常舒服.

**Comment by Qifull** [comment]
> **深色模式很统一**

...  _这么大个绿色_ 你的主题是绿色吗

**Comment by Qifull** [comment]
我的问题,我的问题

**Comment by gurecn** [comment]
当前应用没有更新到应用商店，再完善一些后会发布到F-Droid上，届时就能解决大部分版本不一致的问题了。
