### ISSUE TITLE
没错，它又来了，9键按键卡顿

### ISSUE THREAD

**Issue by puaxmr** [gurecn/YuyanIme#167]
我看到有人反馈过了，https://github.com/gurecn/YuyanIme/issues/149
使用目前最新版本，v20241113.11，依旧存在，机型，红米k20系列，也是按下后的那个黑色阴影延迟，造成卡顿的感觉，不顺滑，每一次打字都表示心塞，我是9键党，看到语燕表示欣喜若狂，希望开发能够解决，我将常驻语燕，感谢，作为日常使用，希望顺滑和能够句子联想吧，其余目前感觉都挺好的。希望开发能够采纳。感谢。

**Comment by puaxmr** [comment]
出离线版和在线版供选择这个操作很好，我个人偏向使用离线版，看个人需求。还有一个点，比如我打语燕，yuyan是联想不起来的，我得分开打，语和燕，那么在第二次输入yuyan，能出现语燕这个词语吗，不知道你们叫啥，感觉这样更方便。希望开发采纳。谢谢

**Comment by demoAlitalia** [comment]
荣耀x20同款问题，我将常驻语燕，感谢。

**Comment by gurecn** [comment]
卡顿的问题请大家使用[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)测试一下，有问题请及时反馈。

**Comment by gurecn** [comment]
> 出离线版和在线版供选择这个操作很好，我个人偏向使用离线版，看个人需求。还有一个点，比如我打语燕，yuyan是联想不起来的，我得分开打，语和燕，那么在第二次输入yuyan，能出现语燕这个词语吗，不知道你们叫啥，感觉这样更方便。希望开发采纳。谢谢

您如果是先输入  `yu` ，选择雨，再输入 `yan` ，选择燕，那么输入法是不会记录雨燕这个自造词语的。需要您直接输入`yuyan`，这时依次选择雨燕这两个字，也可以借助侧滑栏的拼音依次选择`yu`，`yan`实现雨燕这两个字的输入。如此下次再输入`yuyan`时，会自动联想到雨燕。

**Comment by keeejiii** [comment]
> 卡顿的问题请大家使用[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241129.14)测试一下，有问题请及时反馈。

新版本丝滑多了

**Comment by puaxmr** [comment]
> > 出离线版和在线版供选择这个操作很好，我个人偏向使用离线版，看个人需求。还有一个点，比如我打语燕，yuyan是联想不起来的，我得分开打，语和燕，那么在第二次输入yuyan，能出现语燕这个词语吗，不知道你们叫啥，感觉这样更方便。希望开发采纳。谢谢
> 
> 您如果是先输入 `yu` ，选择雨，再输入 `yan` ，选择燕，那么输入法是不会记录雨燕这个自造词语的。需要您直接输入`yuyan`，这时依次选择雨燕这两个字，也可以借助侧滑栏的拼音依次选择`yu`，`yan`实现雨燕这两个字的输入。如此下次再输入`yuyan`时，会自动联想到雨燕。

感谢解答
