### ISSUE TITLE
组词时候选字不全问题

### ISSUE THREAD

**Issue by TomoeMami** [gurecn/YuyanIme#169]
如「黑阈」一词，当第一个字选中黑时，第二个字候选中没有「阈」这个字。

![Screenshot_2024-11-27-14-21-49-30_d97e70df473fd2e37898d35a3e82c2a2](https://github.com/user-attachments/assets/a20bf391-7ded-40e2-b606-f0b8d78816a9)

**Comment by flyear8** [comment]
遇到同样的问题，分开打单个字是全的，组合到一起选字的时候就会字库不全，有些字没有。
v20241113.12版本离线版九宫格拼音

**Comment by TomoeMami** [comment]
https://github.com/gurecn/YuyanIme/issues/152

同一问题，合并issue

**Comment by gurecn** [comment]
感谢反馈。该问题已修复，预计会在明天发布修复版本。
