### ISSUE TITLE
输入英文后紧接着输入符号会导致前面输入的字被清空

### ISSUE THREAD

**Issue by ace115** [gurecn/YuyanIme#17]
就是英文还有下划线的状态下输入符号，中文没有此问题

**Comment by gurecn** [comment]
感谢反馈，20240822（明天）会发布新版本解决该问题。

**Comment by gurecn** [comment]
该功能在最新的[v4.3.3版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.3.3)已经优化，邀请您体验。
