### ISSUE TITLE
建议嵌入whisper以支持离线语音识别

### ISSUE THREAD

**Issue by Liu8Can** [gurecn/YuyanIme#171]
可以考虑嵌入OpenAI Whisper来支持离线语音识别，使得雨燕成为一个六边形战士。
可以借鉴的项目
- https://github.com/vilassn/whisper_android
- https://github.com/soupslurpr/Transcribro

目前他们默认使用的最小的whisper-tiny模型，对中文识别效果不太好，可以考虑更大的模型。然而这样的弊端可能是导致软件安装包过大。

**Comment by PlexPt** [comment]
要500M的模型

**Comment by gurecn** [comment]
语音功能需要继续调研一下。大的话会导致安装包过大，小的话会导致体验很差。我会纳入到后续规划，感谢你们的反馈。

**Comment by shandianchengzi** [comment]
> 语音功能需要继续调研一下。大的话会导致安装包过大，小的话会导致体验很差。我会纳入到后续规划，感谢你们的反馈。

这个项目也值得参考，他们提供了offline和online两个版本，使用阿里云的API，整体使用过程不算复杂，可以支持用户自己申请API，识别准确率是我用过的所有语音输入里面最准确的，还有热词词库自定义之类的
https://github.com/HaujetZhao/CapsWriter-Offline

**Comment by adk23333** [comment]
> 大的话会导致安装包过大，小的话会导致体验很差。

可以先实现功能，然后让有需要的用户自行导入合适的模型。
手写同理
