### ISSUE TITLE
请问怎么打开词语联想啊？没找到选项。

### ISSUE THREAD

**Issue by klxq520** [gurecn/YuyanIme#172]
我一般打五笔画，比如输入“明”，然后可以持续点击“天”“会”“更”“好”，非常需要这个功能。

**Comment by us0g** [comment]
同样没找到，简单的联想功能还是挺好用的希望可以有

**Comment by gurecn** [comment]
当前还不支持词语联想功能，这个功能不是rime内置的，需要修改rime内部实现，后续会加入，请耐心等待哈。

**Comment by drw2005** [comment]
强烈希望尽快上线这个功能。

**Comment by gurecn** [comment]
联想功能已实现，会在下个版本发布。请关注版本发布及时更新。
