### ISSUE TITLE
卡顿问题有所改善但仍有

### ISSUE THREAD

**Issue by keeejiii** [gurecn/YuyanIme#177]
，![Screenshot_2024_1130_005959](https://github.com/user-attachments/assets/ea9da0ec-226d-47a0-a5d5-a2548d5b15bd)

当候选字变多的时候，这时候再打字就卡顿了，GIF不动了不是暂停，而是卡着。。

**Comment by gurecn** [comment]
您是什么机型和系统？

**Comment by keeejiii** [comment]
> 您是什么机型和系统？

机型: iqoo z9 turbo
系统: OriginOS4

**Comment by laurenafolk** [comment]
确实存在这个问题，note11tpro 类原生

**Comment by keeejiii** [comment]
> 确实存在这个问题，note11tpro 类原生

还有一个问题，表情排序不正常
![Uploading Screenshot_2024_1201_222408.png…]()

**Comment by wubidao** [comment]
我电视性能低，没这些问题。厂家自改的系统问题多多

**Comment by gurecn** [comment]
> > 确实存在这个问题，note11tpro 类原生
> 
> 还有一个问题，表情排序不正常，表情间会有空白，空白部分不是没有表情，而是能点出表情的 ![Screenshot_2024_1201_222408](https://private-user-images.githubusercontent.com/132086188/391339979-2717146a-f672-4d9f-a79e-69ae7cae234d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDMxODIsIm5iZiI6MTczMzU0Mjg4MiwicGF0aCI6Ii8xMzIwODYxODgvMzkxMzM5OTc5LTI3MTcxNDZhLWY2NzItNGQ5Zi1hNzllLTY5YWU3Y2FlMjM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMzQxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGEzOGEyYTljMjRlZjM2MmNmOGU3MWI2NDg1MTU4MGZmM2Q2YzJkNzgyNzExYzM5MTVjZGQ2MThhNzkxZmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wHH65RmfXug-NA1TIuDc7jxS480pjbFMBSQMAFD1W_c)

新版本优化了候选词布局，请查看表情是否显示正常了？

**Comment by keeejiii** [comment]
> > > 确实存在这个问题，note11tpro 类原生
> > 
> > 
> > 还有一个问题，表情排序不正常，表情间会有空白，空白部分不是没有表情，而是能点出表情的 ![Screenshot_2024_1201_222408](https://private-user-images.githubusercontent.com/132086188/391339979-2717146a-f672-4d9f-a79e-69ae7cae234d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDMxODIsIm5iZiI6MTczMzU0Mjg4MiwicGF0aCI6Ii8xMzIwODYxODgvMzkxMzM5OTc5LTI3MTcxNDZhLWY2NzItNGQ5Zi1hNzllLTY5YWU3Y2FlMjM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMzQxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGEzOGEyYTljMjRlZjM2MmNmOGU3MWI2NDg1MTU4MGZmM2Q2YzJkNzgyNzExYzM5MTVjZGQ2MThhNzkxZmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wHH65RmfXug-NA1TIuDc7jxS480pjbFMBSQMAFD1W_c)
> 
> 新版本优化了候选词布局，请查看表情是否显示正常了？

现在只有最后一行才会不正常
![Screenshot_2024_1207_112515](https://github.com/user-attachments/assets/6c2c975f-e31a-4cfb-bc9e-7e80fbc88a35)
