### ISSUE TITLE
全面屏左右功能键不能使用

### ISSUE THREAD

**Issue by zhl111** [gurecn/YuyanIme#178]
三星s23u，点按无任何反应

而且其扩展功能与顶排功能键重复，实用性大减

**Comment by gurecn** [comment]
我发现三星手机全面屏会在键盘弹出时默认出现系统导航条，此时会与雨燕输入法全面屏导航栏部分重合，导致按键和滑动功能失效。解决方案为点击键盘雨燕图标，选择调节键盘，向上拖动下方的移动键盘图标将键盘拉升，此时能解决问题。如果感觉拉升后太高，可以到设置中关闭全面屏键盘优化功能。

**Comment by gurecn** [comment]
标点符号有更简单的的方式就是上划输入。当前考虑长按默认选择字母，如果是全键盘，默认选择和键盘上不同的大小写，比如长按小写键盘，默认选择大写。
符号的问题能截个图标注一下吗？我没看看明白。

**Comment by gurecn** [comment]
标点符号有更简单的的方式就是上划输入。当前考虑长按默认选择字母，如果是全键盘，默认选择和键盘上不同的大小写，比如长按小写键盘，默认选择大写。
符号的问题能截个图标注一下吗？我没看看明白。

**Comment by gurecn** [comment]
符号问题及长按默认选中上划符号功能已经修复，请使用新版本进行体验。感谢您的支持
