### ISSUE TITLE
能否将输入法功能添加到候选框！

### ISSUE THREAD

**Issue by kiwiXZRO** [gurecn/YuyanIme#18]
如图所示，希望作者大大能够在候选框中增加自定义添加输入法功能，这样在日常使用中提高操作便利性、也更美观。
  另外希望有考虑做文字翻译功能，接入国外翻译引擎？
![Screenshot_20240823_005831](https://github.com/user-attachments/assets/e0882dae-6681-43e4-9f58-943687234485)
![Screenshot_20240823_010056](https://github.com/user-attachments/assets/713233d0-4fb4-47d0-8bf8-1037aaa2f455)

**Comment by gurecn** [comment]
谢谢您的反馈。
如图所示，希望作者大大能够在候选框中增加自定义添加输入法功能，这样在日常使用中提高操作便利性、也更美观。
> 该功能已列入后续功能，本周功能已开发完成。可能要下周五版本实现了。请您关注。

另外希望有考虑做文字翻译功能，接入国外翻译引擎？
> 由于当前雨燕输入法定位，不获取任何权限，不上传任何信息。因此暂无计划接入互联网功能。这个需求我作为一个特殊需求记录，后续产品规划作为一个考量。

**Comment by gurecn** [comment]
v20240914.15版本增加输入法菜单栏功能，邀请您体验，期待您的反馈。
