### ISSUE TITLE
在微信怎么换行哦

### ISSUE THREAD

**Issue by Ash7z2** [gurecn/YuyanIme#180]
手机端微信设置了回车键发送之后怎么换行哦

**Comment by gurecn** [comment]
您是在微信发消息时，右下角显示的是`发送`按钮吗？进入微信，选择我的−设置−聊天−开启`使用独立的发送按钮`，此时聊天时，键盘右下角发送键会变成换行键。

**Comment by gurecn** [comment]
这是微信的机制，输入法要么是兼容微信输入框。后续雨燕输入法规划有判断在微信发送消息界面时，表情展示微信特效表情，到时候会同时考虑这个问题。

**Comment by Ash7z2** [comment]
我是想着能不能实现长按是发送按键能弹出换行哦，这样能方便一点，毕竟平时使用换行的频率不算很高，拜托了！

**Comment by gurecn** [comment]
这个可以，我记录一下，下个版本加入。

**Comment by gurecn** [comment]
[新版本](https://github.com/gurecn/YuyanIme/releases)已加入长按回车键输入换行功能，邀请您体验。

**Comment by Ash7z2** [comment]
![1000071876](https://github.com/user-attachments/assets/3004d3a0-4dbd-4c3a-9982-429813ac6abd)
![1000071877](https://github.com/user-attachments/assets/14c8f33c-4219-49ae-b4f8-e710c3cd319f)
普通键盘下，用上面那排数字的话有可能会出现下面那个空白哦，有时候一直切换都不会恢复

**Comment by Ash7z2** [comment]
![1000071879](https://github.com/user-attachments/assets/166415d1-fd5d-40aa-a8aa-5365dc2cc464)
。这个取消数字键的下巴又长出来了，还有就是我重新安装是不是不会保存以前的设置的。

**Comment by gurecn** [comment]
这个问题有人反馈了，我会尽快出一个临时版本修复这个问题。
