### ISSUE TITLE
新版本很好用，很顺滑，顺便再提一个隐私安全的想法。

### ISSUE THREAD

**Issue by puaxmr** [gurecn/YuyanIme#184]
语燕理念非常棒了，也很好用，我有个想法，粘贴板，虽然本身安全性满足了，但无法防止现在各种流氓app读取你的粘贴内容，恶意app甚至会替换你的粘贴内容，能否在输入法这层面，组织app读取粘贴板的内容，或者对方读取也是乱码而不会明文被读取，这样我觉得算是更加保护用户隐私，也能算到时候语燕输入法的一大特点，不知道实施难度，望开发采纳。希望语燕越来越好，简洁安全，不忘初心。

**Comment by wubidao** [comment]
是阻止，不是组织。

**Comment by gurecn** [comment]
剪切板是系统功能，输入法监听系统复制时，从系统读取最新复制内容并存储到输入法自身数据库中。若此时将复制的内容从系统中移除，会导致无法使用系统长按粘贴，只能在雨燕输入法剪切板粘贴，这个可能会影响一些用户的使用习惯。
