### ISSUE TITLE
主题不要渐变

### ISSUE THREAD

**Issue by wubidao** [gurecn/YuyanIme#185]
背景左右颜色有差异时，看左边眼球肌肉一个状态，看右边又一个状态，肌肉反复变化导致眼睛酸、不适。
候选词字大小与顶栏几个图标大小尽量接近，
在我的安卓10电视电视上表现真的不错。悬浮和单手用于调整面板大小，减少了鼠标移动量。
小鹤双拼大大减少了击键量。显示的韵母太漂亮了。
这可能是支持电视最好的输入法。远离电视原因之一就是打字困难。您为雨燕找到了突破口，声称支持电视是个好主意。
专门开发一个电视版也不错。

**Comment by gurecn** [comment]
感谢您的支持，主题的问题可以在设置，主题，主题选择中更换默认深色和亮色主题。

**Comment by swh922** [comment]
> 感谢您的支持，主题的问题可以在设置，主题，主题选择中更换默认深色和亮色主题。

![Screenshot_20241203-100332_Alpha Launcher.png](https://github.com/user-attachments/assets/72bb794c-fd7e-4f75-a507-bf2b02daa2af)

非常喜欢这个色调，希望给它加上按键边框，设置里开启边框按钮对它无效

**Comment by gurecn** [comment]
感谢你们的建议，新版本已经将默认主题替换成非渐变主题。主题边框无效的问题[新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241206.20)同时已经解决，欢迎你们体验。
