### ISSUE TITLE
能不能把那个键盘拖动放上面

### ISSUE THREAD

**Issue by MicroNeutron** [gurecn/YuyanIme#186]
如题 卡底下出不来了😭
![Screenshot_20241203_001343_com huawei search](https://github.com/user-attachments/assets/1269f7d5-01a6-43a4-9d8b-834c2da78f62)

**Comment by gurecn** [comment]
可以点击键盘左上角雨燕图标−键盘调节−拖动下方下方的移动图标移动键盘。
