### ISSUE TITLE
bug反馈：繁体开关关了，候选词界面仍有繁体，简繁都有（如图）

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#187]
![Screenshot_20241203-225259_微信.png](https://github.com/user-attachments/assets/3a617607-c616-4e1d-94cb-c2678eabca61)

最新版本，关掉繁体开关，有的字显示繁体，有的不显示

**Comment by gurecn** [comment]
繁体字被作为生僻字放到词库中，避免出现部分场景下无法找到字的问题。新版本增加了大字表`Unihan 字库40K 大字库`，解决生僻字问题。
