### ISSUE TITLE
可以加入同文和小企鹅输入法等导入其他输入方案的功能吗

### ISSUE THREAD

**Issue by neun29** [gurecn/YuyanIme#189]
很喜欢雨燕输入法的简洁上手就用的功能，是否可以加入同文和小企鹅等可以导入其他输入方案的功能，因为使用的是音形方案。

**Comment by gurecn** [comment]
感谢您的支持，当前雨燕输入法暂不支持自定义输入方案，仅支持内置方案。雨燕的初衷是为了做一款安装即可使用、输入体验良好的输入法，当前尚未规划支持自定义方案的计划，当然我会不断完善和丰富输入方案以满足不同人群的需求。若需要自定义方案的话，个人还是建议使用小企鹅来实现。
