### ISSUE TITLE
希望双拼能增加上屏是输入字母的选项

### ISSUE THREAD

**Issue by zhl111** [gurecn/YuyanIme#19]
双拼输入时经常忘记先要切换成英文输入法，这是以前的习惯下意识输入了英文，但因为显示的是全拼，就不得不重新输入。而且，双拼在输入一段话的时候，如果误打错了一个字母，想要修正时就很不直观。第三，能否增加空格键移动光标修改输错字母的功能。

**Comment by gurecn** [comment]
双拼输入时经常忘记先要切换成英文输入法，这是以前的习惯下意识输入了英文，但因为显示的是全拼，就不得不重新输入。而且，双拼在输入一段话的时候，如果误打错了一个字母，想要修正时就很不直观。
> 上屏输入字母的功能我调研一下，可以的话我会加入到设置中。

第三，能否增加空格键移动光标修改输错字母的功能。
> 当前空格键移动是移动输入框中光标位置功能，暂时不支持修改字母功能。两者会产生冲突。我会调研一下其他输入法的处理逻辑。

感谢您的反馈。

**Comment by gurecn** [comment]
好的，这个功能我记录一下。感谢您的反馈。

**Comment by gurecn** [comment]
v20240914.15版本增加双拼模式显示`完整拼音`与`输入按键`切换功能，邀请您体验，期待您的反馈。
