### ISSUE TITLE
作者可以考虑加一个类似小企鹅输入法或者谷歌输入法的内嵌密码键盘吗

### ISSUE THREAD

**Issue by zyt174** [gurecn/YuyanIme#190]
类似小企鹅输入法那种，与键盘集成，密码管理软件的自动填充会显示为键盘的内联选项。
![Uploading Screenshot_20241204_015650_com.yujian.ResideMenuDemo.jpg…]()

**Comment by zyt174** [comment]
![Uploading Screenshot_20241204_015650_com.yujian.ResideMenuDemo.jpg…]()

**Comment by zyt174** [comment]
还有就是有一个bug，荣耀老机子，鸿蒙4.0这个版本用起来，打字一段时间最上方工具栏还有字显示栏会无法点击

**Comment by 2LC16** [comment]
感觉没必要，手机系统自带的密码键盘功能不会调用输入法。你可以找找看

**Comment by gurecn** [comment]
工具栏和候选词无法点击的问题麻烦您关注一下出现的场景，我也会继续尝试复现该问题。
