### ISSUE TITLE
中文标点符号界面无书名号

### ISSUE THREAD

**Issue by 2LC16** [gurecn/YuyanIme#196]
仅有＜＞，无有《》

**Comment by gurecn** [comment]
发现这个问题了，下周版本修复。当前版本可以向左滑动界面，到`括号`页面选择书名号

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
