### ISSUE TITLE
深色模式调整影键盘高度

### ISSUE THREAD

**Issue by famous7928** [gurecn/YuyanIme#198]
故障如视频出现，已经反复测试多次，故障依旧，键盘震动很棒🌝
视频大于10M我就上传123网盘分享了
https://www.123684.com/s/UY39-jUtaH?提取码:1024

**Comment by gurecn** [comment]
我看了您的视频，是切换深色主题就会将键盘拉伸吗？或者复现概率有多大？麻烦您关注一下出现这种情况前做了什么操作，我从来没遇到过类似的情况。测试了几次没有复现。
您的机型是哪一款？什么系统？

**Comment by famous7928** [comment]
![Screenshot_2024-12-06-20-44-16-072_com.android.settings.jpg](https://github.com/user-attachments/assets/af2e347e-e80e-4abe-983f-0391880c70ad)
机型以及系统版本如图，此bug开启深色模式以及数字行功能都会触发https://github.com/user-attachments/assets/08607492-5f2d-4717-92fc-4f2ba39a2154



> 我看了您的视频，是切换深色主题就会将键盘拉伸吗？或者复现概率有多大？麻烦您关注一下出现这种情况前做了什么操作，我从来没遇到过类似的情况。测试了几次没有复现。
> 您的机型是哪一款？什么系统？

**Comment by gurecn** [comment]
好的，我找类似机型测试一下。

**Comment by famous7928** [comment]
> 好的，我找类似机型测试一下。

非常感谢，辛苦了

**Comment by famous7928** [comment]
刚刚找redmi k70u测试，故障依旧，系统版本如图![Screenshot_2024-12-06-21-04-53-014_com.android.settings_090502.jpg](https://github.com/user-attachments/assets/14fed73f-1688-45cc-aceb-cb951f57b2ae)

测试视频如以下视频，测试过程中已经关闭系统自带的安全键盘，全面屏优化以及语燕输入法全面屏键盘优化https://github.com/user-attachments/assets/6c00909d-e5e7-44f5-b78c-ae2ac252c99e


> 好的，我找类似机型测试一下。

**Comment by gurecn** [comment]
明白了，我发现了，是雨燕输入法全面屏键盘导航栏占位的问题，开启雨燕输入法全面屏键盘优化的话没问题。下个版本修复该问题。

**Comment by gurecn** [comment]
已紧急更新一个版本，请下载[最新版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241206.22)进行使用，感谢您的反馈。
