### ISSUE TITLE
离线手写

### ISSUE THREAD

**Issue by atlantis451** [gurecn/YuyanIme#20]
一些离线手写库
https://kiang.org/jordan/software/hanzilookup/ 中文
https://github.com/tegaki/tegaki 中文和日语
https://github.com/gugray/HanziLookupJS 中文 Javascript
https://gitee.com/hebinq/shuoxie 中文
https://github.com/quen/kanjirecog/tree/android 日语 Java library
https://github.com/Saren-Arterius/google-chinese-handwriting-ime Google中文
https://popolon.org/gblog3/?p=447&lang=en  Linux的FOSS手写识别输入

**Comment by gurecn** [comment]
感谢您的贡献，我研究一下这些项目，如果可以的话，我将手写功能尽快补充上。
再次感谢您的反馈。

**Comment by gurecn** [comment]
感谢您的建议，以上开源项目我均体验了，但是识别效果均不理想。
最新版本雨燕输入法已集成汉王收费手写云识别服务，基本能够满足日常输入需求。后续我会继续调研比较好用的离线输入方案。若您有更好的推荐也期待您的继续反馈。

**Comment by ghost** [comment]
@gurecn  你好 google 手写模型 可离线使用. https://developers.google.com/ml-kit/vision/digital-ink-recognition
> 这可以 在 飞燕输入法 在线版使用. 或者 手动下载中文模型后 捆绑到 离线版
使用google 手写模型 app 参考 https://github.com/yonasoft/jade-dictionary-android2
