### ISSUE TITLE
bug 反馈 & 功能建议

### ISSUE THREAD

**Issue by xkayp** [gurecn/YuyanIme#203]
![video_2024-12-07_22-40-11-1](https://github.com/user-attachments/assets/ecd7e778-239c-491b-91e1-d8c6e5360217)
如图，中文/英文键盘调节时，只对当前键盘有效，导致另一种键盘显示出现bug影响使用
![v20241113 12](https://github.com/user-attachments/assets/39bd4ec8-b802-40fe-885b-9bd84697c19a)
![v20241129 14 ](https://github.com/user-attachments/assets/01d852e6-584e-408f-b780-7fda83ce0307)
![v20241206 22](https://github.com/user-attachments/assets/ca782772-7436-45ad-b670-c6d532edb5a7)
最近三个版本的工具栏越来越宽，工具栏图标也越来越大，观感也越来越不协调，希望能进一步引入个性化工具栏宽度和图标大小的功能

**Comment by gurecn** [comment]
收到反馈，下个版本修复该问题。

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
