### ISSUE TITLE
这次反应一下符号的问题

### ISSUE THREAD

**Issue by CitizenScyu** [gurecn/YuyanIme#204]
标点符号,最近使用里面无法删除,分辨不清中英文的,点错了都出现在里面。还有就是能不能让用户自己选择打开标点符号默认进入中文符号还是英文符号,个人打字需求不同,研发辛苦,祝顺利。
还有就是一个小问题,收起键在首页的时候,剩一点点了
![Screenshot_2024-12-08-03-20-31-370_mark via](https://github.com/user-attachments/assets/94e13109-09e9-46bd-ab55-1bf3e6c0abc3)

**Comment by parauni** [comment]
请问收起键可以自定义吗，我的收起键不见了，实在找不到在哪里打开
![Screenshot_2024-12-08-09-04-16-176_com microsoft emmx-edit](https://github.com/user-attachments/assets/dd1aa5fa-47f2-4a5f-bba0-89cf06d9e5dd)

**Comment by parauni** [comment]
> 请问收起键可以自定义吗，我的收起键不见了，实在找不到在哪里打开 ![Screenshot_2024-12-08-09-04-16-176_com microsoft emmx-edit](https://private-user-images.githubusercontent.com/128904709/393555403-dd1aa5fa-47f2-4a5f-bba0-89cf06d9e5dd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjcyNjIsIm5iZiI6MTczMzYyNjk2MiwicGF0aCI6Ii8xMjg5MDQ3MDkvMzkzNTU1NDAzLWRkMWFhNWZhLTQ3ZjItNGE1Zi1iYmEwLTg5Y2YwNmQ5ZTVkZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQwMzAyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWIyNTdmNTg1NTJkZDViMTVmMWU0YjdkZjI1NWFmZjFlZGNkNDJhMDQyZGM3MWJhZjJmOWEyOTZhODNmYWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9bCA-jB84mjZKFRdDv4eB0nC9KNVI3dK4jf6mvUJ1zw)


我发现清除数据后收起按钮就有了，然后找了半天，在雨燕的Android/data目录里修改xml文件把收起按钮加回来了："keyboard_bar_menu_common">CloseSKB</string>，就是这个CloseSKB。不知道为什么之前莫名其妙消失了

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
