### ISSUE TITLE
自定义收起按钮

### ISSUE THREAD

**Issue by parauni** [gurecn/YuyanIme#206]
请问收起键可以自定义吗，我的收起键不见了，找不到在哪里打开，键盘设置和定制工具栏都没有
![Screenshot_2024-12-08-09-04-16-176_com microsoft emmx-edit](https://github.com/user-attachments/assets/f1458d61-fcc8-48da-9897-da926cef38ca)

我发现清除数据后收起按钮就有了，然后找了半天，在雨燕的Android/data目录里修改xml文件把收起按钮加回来了："keyboard_bar_menu_common">CloseSKB，就是这个CloseSKB。不知道为什么之前莫名其妙消失了

**Comment by flyear8** [comment]
遇到过相同的问题，从中途某一个版本开始的，一直更新一直都不会出现。卸载重装后按钮回来了。但是，之前积累的个人词库重装后也没有了。希望卸载重装后个人词库能保留

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
