### ISSUE TITLE
@         这个符号的编码不对

### ISSUE THREAD

**Issue by tiarawph** [gurecn/YuyanIme#207]
首先对雨燕输入法的开发者表示由衷的感谢。在保护隐私方面是可以值得信任的。软件也很好用。我没看到有donate的地方。
我在使用过程中发现一个问题。 @这个符号的编码应该是错误的。 我用雨燕输入法在输入邮箱地址或者是密码的时候(我密码中用了西文@)，都被提示错误。
我用的是离线版本。请检查纠正一下，谢谢

**Comment by gurecn** [comment]
你在微信群聊中输入@可以唤起选择成员吗？或者用的哪个邮箱输入界面，我去试一下

**Comment by laurenafolk** [comment]
> 你在微信群聊中输入@可以唤起选择成员吗？或者用的哪个邮箱输入界面，我去试一下

测试，能唤起微信所有人，但是好像显示不一样😂，不过不存在

**Comment by iminto** [comment]
你选错了，选了中文的@符号，你需要选英文的@

**Comment by tiarawph** [comment]
谢谢，感谢你为大家的付出。

┣█萇老⌒う塟嫒鎵鏃ζ ***@***.***> 于2024年12月11日周三 11:24写道：
