### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#211]
同时打两个字尤其是非常用词语的时候，滑动栏选了第一个字后，第二个字需要手动往前滑动选择，而不是默认从头选择，比如‘大背’，如动图
![Video_20241209_074609_11.gif](https://github.com/user-attachments/assets/f5b55848-6007-48b1-ab09-b29942ea0519)

**Comment by gurecn** [comment]
收到反馈，下个版本修复该问题。

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
