### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by qixi202303** [gurecn/YuyanIme#213]
右下角的剪贴板按钮图标和切换输入法的按钮重叠了

**Comment by qixi202303** [comment]
![Screenshot_2024-12-09-21-41-50-10_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/user-attachments/assets/6f2aac97-3b5d-4ec6-af81-d31688665013)

**Comment by gurecn** [comment]
下个版本修复该问题，当前版本可以点击左上角雨燕图标，选择键盘调节-向上拖动下方移动按钮避免覆盖。或者进入设置-关闭全面屏键盘优化

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)

**Comment by qixi202303** [comment]
> 新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)

如果全面屏键盘设置里左边/右边，有一个设置为无功能，输入法就会调用不出来

**Comment by gurecn** [comment]
收到反馈，下个版本修复该功能。
