### ISSUE TITLE
常用语的需求！！

### ISSUE THREAD

**Issue by dust2k** [gurecn/YuyanIme#217]
安装后发现界面有点不是很爽利，但没问题，只是习惯于用常用语，试图添加和使用了一下，如下问题希望大佬考虑加进来：
1. 常用语分组，我大概有100多条常用语，堆在一起实在难受
2. 根据使用习惯，我希望能拖动排序
3. 能删除，目前没找到怎么删
4. 如果知道存储的数据文件在哪里，去那里改也行，但没找到
5. 前面好多人说了，最好能跟某云，某webdav同步啥啥的。。。

**Comment by Azreulo** [comment]
3.左滑就能删除，不过UI逻辑有点问题，左滑后会退出常用语编辑界面。建议推出后停留在常用语编辑界面。

**Comment by gurecn** [comment]
常用语删除的逻辑已经优化，请体验。常用语不是输入法主要功能，这些需求我会记录，但是优化的优先级可能会比其他需求更低一些，请耐心等待哈
