### ISSUE TITLE
自动切换悬浮键盘

### ISSUE THREAD

**Issue by zhangyusheng211** [gurecn/YuyanIme#22]
不定时出现，正常的键盘模式自动切换为悬浮键盘，而且设置里关不掉，用着很突兀

**Comment by zhangyusheng211** [comment]
![image](https://github.com/user-attachments/assets/f84e4726-1549-45e0-ac95-a9362d1458ef)

**Comment by gurecn** [comment]
好的，这个问题我复现出来了，当频繁切、快速换横竖屏时，概率导致状态错乱：错误地把竖屏判断为横屏，横屏强制悬浮模式且不可关闭。当前出现该问题时，正常速度切换一次横竖屏即可恢复。
下个版本修复该问题。
感谢您的反馈。

**Comment by gurecn** [comment]
好的，这个问题我复现出来了，当频繁切、快速换横竖屏时，概率导致状态错乱：错误地把竖屏判断为横屏，横屏强制悬浮模式且不可关闭。当前出现该问题时，正常速度切换一次横竖屏即可恢复。
下个版本修复该问题。
感谢您的反馈。

**Comment by gurecn** [comment]
新版本已加入该功能，期待您的反馈[v20240829.09](https://github.com/gurecn/YuyanIme/releases/tag/v20240829.09)
