### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by CitizenScyu** [gurecn/YuyanIme#226]
在打骗过你三个字的时候,打完pianguoni,然后去选pian的时候,会闪退

https://github.com/user-attachments/assets/29074304-d66e-4bd1-a28a-db117e31e9a7

**Comment by gurecn** [comment]
收到反馈，下个版本会同步解决该问题。

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
