### ISSUE TITLE
当键盘高度过低时，键盘下方UI会被遮挡

### ISSUE THREAD

**Issue by Gralent** [gurecn/YuyanIme#229]
如图所示：
![Screenshot_2024-12-17-09-56-02-23_ae1f93045b87aacac90efbb155289789](https://github.com/user-attachments/assets/cc97241f-3d8d-41da-8eba-83fe94153b27)
语燕输入法版本：离线版 20241206.22
手机型号：一加ACE 3v
系统版本：Color OS 15.0

**Comment by Gralent** [comment]
具体是切换到数字或者英文键盘，然后调节键盘高度，再返回中文键盘，发现UI排版异常，具体请看视频：

Uploading Record_2024-12-17-19-55-53.mp4…

**Comment by gurecn** [comment]
收到，复现出来了，下个版本修复该问题。

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)
