### ISSUE TITLE
添加切换输入法

### ISSUE THREAD

**Issue by wnarutou** [gurecn/YuyanIme#23]
希望能够加入切换输入法功能，因为使用场景不一样需要使用不同输入法，使用同文、小企鹅发展是存在这个功能。

**Comment by gurecn** [comment]
为什么要频繁切换输入法呢？如果雨燕有使用不便之处希望您能反馈出来，我会及时修复的。
快捷切换输入法功能系统支持。可以在弹出键盘时下拉通知栏切换或在弹出键盘时导航栏点击键盘按钮切换。

**Comment by chengnan049** [comment]
刚开始用雨燕感觉很难用，缺失功能太多了，在如下列出了。最吸引我的是 emoji 联想全面，比讯飞好多了，不过用了一小会儿就换讯飞了，前天晚上刷机讯飞没备份上，就用雨燕了，一天下来体验还能接受，但愿项目越来越好
1.相比其他主流输入法按键字体过小，显得按键拥挤
2.逗号需要使用符号面板才能输入
3.无法关闭英文单词输入（周五修复）
4.符号成对输入
5.独立的 emoji 页面
6.没有提供英文单词输入后空格开关
7.没有工具栏
8.中文输入按字筛选
9.符号面板没有锁定按钮

**Comment by WayneY** [comment]
> 为什么要频繁切换输入法呢？如果雨燕有使用不便之处希望您能反馈出来，我会及时修复的。 快捷切换输入法功能系统支持。可以在弹出键盘时下拉通知栏切换或在弹出键盘时导航栏点击键盘按钮切换。

切换输入法的场景也挺多的吧，比如有时候需要用到日语之类的别的语言输入。你说的下拉通知栏切换或者导航栏切换看得我有点懵逼。通知栏和导航栏还能切输入法？没看到有类似的按钮或者图标啊。

**Comment by gurecn** [comment]
[雨燕输入法v20240907.08](https://github.com/gurecn/YuyanIme/releases/tag/v20240907.08)已添加长按`中英文切换按键`，修改输入法功能，请体验。可以在设置-键盘-键盘-键盘设置中开启和关闭相关功能。感谢您的反馈，请您体验。

**Comment by gurecn** [comment]
[雨燕输入法v20240907.08](https://github.com/gurecn/YuyanIme/releases/tag/v20240907.08)已添加长按`中英文切换按键`，修改输入法功能，请体验。可以在设置-键盘-键盘-键盘设置中开启和关闭相关功能。感谢您的反馈，请您体验。
