### ISSUE TITLE
九键模式下打出声母为Z的字，然后在左侧单独选择字母Z，会导致输入法崩溃

### ISSUE THREAD

**Issue by Gralent** [gurecn/YuyanIme#230]
如视频所示：

https://github.com/user-attachments/assets/16587b22-67ce-4ee2-9d61-bce14334524b

语燕输入法版本：离线版 20241206.22
手机型号：一加ACE 3v
系统版本：Color OS 15.0

**Comment by gurecn** [comment]
该问题已修复，会在最新版本合入，请关注版本发布情况。

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
