### ISSUE TITLE
最新版的两个bug

### ISSUE THREAD

**Issue by 2LC16** [gurecn/YuyanIme#234]
一是目前在的手机上打开全面屏优化后键盘无法弹出，在关闭全面屏优化后可以正常弹出键盘
二是全拼和双拼界面的上滑输入的括号是英文括号（）而非中文括号，二者的宽度不一样（半角圆角的区别），另外在中文符号界面的括号也是英文的括号，而且在括号界面的半角和圆角的括号也一样不分

**Comment by 2LC16** [comment]
另外从上个版本升级到最新版之后主题丢失了，常用语也丢失了，有点像卸载后重新装

**Comment by gurecn** [comment]
第一个问题下个版本会修复，当前可以暂时关闭全键盘优化键盘，或进入设置界面-将`左侧功能键、右侧功能键`不要选择为`无功能`。
第二个反馈没有明白，当前新版本在符号和长按弹窗会标记是否是半角符号，我试了一下，中文和英文键盘是没问题的啊。
常用语在新版本已迁移至数据库，后续不会导致重装丢失的情况了，主题丢失的情况是您自己定制的主题吗？到主题设置界面也不存在了吗？

**Comment by 2LC16** [comment]
> 第一个问题下个版本会修复，当前可以暂时关闭全键盘优化键盘，或进入设置界面-将`左侧功能键、右侧功能键`不要选择为`无功能`。 第二个反馈没有明白，当前新版本在符号和长按弹窗会标记是否是半角符号，我试了一下，中文和英文键盘是没问题的啊。 常用语在新版本已迁移至数据库，后续不会导致重装丢失的情况了，主题丢失的情况是您自己定制的主题吗？到主题设置界面也不存在了吗？
是显实圆角半角，但是输出的却都是半角符号()，然后主题丢失是在主题设置界面也找不到我的主题，常用语丢失是整个常用语都恢复默认状态了

**Comment by gurecn** [comment]
你录个视频我看下？我手机上中文是全角（），英文是半角啊？()，您看这两个括号就是分别在中文和英文键盘上滑输入的。

**Comment by 2LC16** [comment]
> 你录个视频我看下？我手机上中文是全角（），英文是半角啊？()，您看这两个括号就是分别在中文和英文键盘上滑输入的。

我想我知道问题所在了，我手机上的字体没有区分符号的全角和半角。非常抱歉占用了您宝贵的时间

**Comment by 2LC16** [comment]
字体为苍耳今楷02w04
