### ISSUE TITLE
安装新版本后，常用语被重置！但看app文件夹里的custom_phrase里面还是原来的常用语

### ISSUE THREAD

**Issue by fromFutureAI** [gurecn/YuyanIme#239]
感谢作者的贡献，挺好的输入法！！

刚安装了最新版本，发现常用语被重置了，但看app文件夹里的custom_phrase里面还是原来的常用语，请问还有办法复原吗？不想一条条重输：）

**Comment by gurecn** [comment]
新版本常用语不再使用文件配置的方式，解决每次安装后文件覆盖导致重置的问题，需要你重新输入，后续升级不会再重置了

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)
