### ISSUE TITLE
英文模式下，输入单个字母或字母数字混输，自动联想补齐，也无法单选字母，导致无法输入密码

### ISSUE THREAD

**Issue by iminto** [gurecn/YuyanIme#24]
发现一个比较严重的问题，输入单个字母或字母数字混输，自动联想补齐，导致无法输入密码。
比如作者用手机浏览器在99fund.com这个网站（其它网站也一样）可以试试输入 “y2h996angxiao” 这个密码

试了一些配置，无法关闭这种自动联想和补齐，无视联想，也会产生一些奇奇怪怪的输入，最终就是无法输入密码。
我输入一个y，再输入一个小数字键盘的2，实际会输入三个字母。。。就种种很怪异的输入
我输入y，再按个空格，密码框会出来5个字符。。。

虽然会有个很小的弹出框，会弹出输入单个字母供点击选择，但是那个框太小太小且靠左，导致根本无法被正确点击到。

最后的解决方式是，遇到输入密码的地方，我就切换为AOSP原生键盘解决的。

**Comment by iminto** [comment]
发现另外一种解决方案：单字滑行输入，虽然输入慢了很多，但是可以解决这个无法输入密码的问题

**Comment by gurecn** [comment]
好的，感谢您的反馈，我测试一下相关功能。本周五版本修复

**Comment by gurecn** [comment]
新版本已加入密码输入框自动关闭英文联想功能，同时英文输入默认关闭追加空格，可自定到`设置`-`输入设置`开启。期待您的使用反馈，[v20240829.09](https://github.com/gurecn/YuyanIme/releases/tag/v20240829.09)
