### ISSUE TITLE
希望能把工具栏按钮做成开关式

### ISSUE THREAD

**Issue by EoP2** [gurecn/YuyanIme#245]
比如按下剪切板按钮后，目前只能通过左上角的折叠按钮返回输入界面，希望也能通过再次按下剪切板按钮来返回。这样可以减少手指在屏幕间游移的频率，更为便捷一些。

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)
