### ISSUE TITLE
英文状态下清空输入框

### ISSUE THREAD

**Issue by famous7928** [gurecn/YuyanIme#248]
英文状态下清空输入框后会自动填充英文联想词https://github.com/user-attachments/assets/9b38b771-c78e-47d2-866c-239de83c7c0b

**Comment by gurecn** [comment]
收到，该问题会在下个版本修复。

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)
