### ISSUE TITLE
分开32、64位，减少arm打包体积

### ISSUE THREAD

**Issue by iminto** [gurecn/YuyanIme#25]
32位安卓几乎没有多少人使用（可能除了某些很老的安卓机顶盒这种设备），我2017年购入的中低端安卓机也是64位的，同时包含这两个系统的so包，导致体积增加了十几M

**Comment by gurecn** [comment]
确实最近的包越来越大了，我想办法裁剪。
当前手机架构有四个`arm64-v8a`,  `armeabi-v7a`, `x86`, `x86_64`，
区分架构打包后可能会导致一部分用户下载安装失败，普通用户很难区分自己的手机到底是哪个架构。

**Comment by chengnan049** [comment]
> 确实最近的包越来越大了，我想办法裁剪。
> 当前手机架构有四个`arm64-v8a`,  `armeabi-v7a`, `x86`, `x86_64`，
> 区分架构打包后可能会导致一部分用户下载安装失败，普通用户很难区分自己的手机到底是哪个架构。

都用这种输入法了 我相信这个能力还是有的

**Comment by gurecn** [comment]
新版本已加入该优化，期待您的反馈[v20240829.09](https://github.com/gurecn/YuyanIme/releases/tag/v20240829.09)
