### ISSUE TITLE
版本构建时间超30天，提示下载最新版本弹窗，会不会影响体验

### ISSUE THREAD

**Issue by iminto** [gurecn/YuyanIme#250]
弹窗频率是一次还是每次都弹？会不会影响体验

**Comment by gurecn** [comment]
当前发现反馈的很多问题是因为未及时更新版本，甚至很多人使用最初版本。按照当前版本发布规划，每个月至少更新两个版本，当超过30天也就意味着中间至少差了两个版本了，这时候建议到GitHub上更新一下版本
