### ISSUE TITLE
横屏悬浮键盘bug

### ISSUE THREAD

**Issue by 2LC16** [gurecn/YuyanIme#253]
偶尔会出现此类情况，键盘无法铺满整个所占的区域，也许是主题的问题？没有开启单手模式
![Screenshot_2024-12-29-12-33-57-79_e39d2c7de19156b0683cd93e8735f348](https://github.com/user-attachments/assets/f569bd13-879d-42b2-bf0d-ebece5d690dc)

**Comment by 2LC16** [comment]
![Uploading Screenshot_2024-12-29-12-33-57-79_e39d2c7de19156b0683cd93e8735f348.jpg…]()

**Comment by gurecn** [comment]
新版本优化了该功能，请在新版再验证一下是否修复。

**Comment by 2LC16** [comment]
> 新版本优化了该功能，请在新版再验证一下是否修复。

新版没有修复，也许是主题的问题？
![IMG_20250101_123816](https://github.com/user-attachments/assets/a391e4d7-2aaa-44c8-bc1a-25460b18e5cb)
