### ISSUE TITLE
玩王者字体非常非常小，如图

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#26]
![Screenshot_20240826-202029_王者荣耀.png](https://github.com/user-attachments/assets/6a60111a-ddc1-4ad1-a6d7-4bc726523e48)

**Comment by swh922** [comment]
> 您是指`12345测试测试`这几个字小吗？这个输入框不是雨燕输入法的吧？您试一下其他输入法有没有这个输入框，字体小不小？

![Screenshot_20240828-133621_王者荣耀.png](https://github.com/user-attachments/assets/7783f26b-a9d2-4f1b-9aa1-f28edfbc2b6f)

这是用讯飞输入法小米定制版测试的，没那么小，貌似也不太大，另外还发现一个bug，有时候想打字键盘莫名其妙会弹不出来

**Comment by gurecn** [comment]
看您这两个截图对比，确实显示不一样。我在游戏里尝试复现一下。
关于键盘弹不出来的情况，麻烦您在下次出现时能记一下怎么操作的，之前之后都做了什么。我尝试复现。

**Comment by swh922** [comment]
> 看您这两个截图对比，确实显示不一样。我在游戏里尝试复现一下。
> 关于键盘弹不出来的情况，麻烦您在下次出现时能记一下怎么操作的，之前之后都做了什么。我尝试复现。
确切的说是弹出来一片空白，如图![IMG_20240828_193236.jpg](https://github.com/user-attachments/assets/82c9fcf3-a295-4d12-871b-238b5bed228f)

![IMG_20240828_193256.jpg](https://github.com/user-attachments/assets/de8bac7d-6a7a-4856-ba04-0dd964e2c8d5)

![Screenshot_20240828-193128_设置.png](https://github.com/user-attachments/assets/b3a47f8d-e339-400a-abdc-7d5c9925fefb)

我设置里装了几个输入法，除了谷歌语音和雨燕，其它几个我都通过灭霸禁止后台自启了，平常打字就用雨燕，不知道具体原因，刚才忙完掏出手机准备打字，又出现这情况，我尝试把谷歌语音也禁用了，雨燕键盘还是弹出空白，只有强行停止它，才能正常呼出键盘

**Comment by gurecn** [comment]
猜测是键盘初始化崩溃了，具体崩溃原因因未加入日志采集功能不好定位。今天我会发布一个版本，修复一个键盘概率初始化崩溃的缺陷，辛苦您尝试一下。下版本我争取添加一个本地日志追踪功能。

**Comment by swh922** [comment]
> 猜测是键盘初始化崩溃了，具体崩溃原因因未加入日志采集功能不好定位。今天我会发布一个版本，修复一个键盘概率初始化崩溃的缺陷，辛苦您尝试一下。下版本我争取添加一个本地日志追踪功能。

我把其它输入法都禁用了，只启用雨燕，还是有弹出键盘空白的问题，发现一个规律，好几次都是手机息屏一段时间后再次解锁准备打字出现的，如果原因不好找，希望加入日志采集功能，我很乐意为您测试

**Comment by swh922** [comment]
> 猜测是键盘初始化崩溃了，具体崩溃原因因未加入日志采集功能不好定位。今天我会发布一个版本，修复一个键盘概率初始化崩溃的缺陷，辛苦您尝试一下。下版本我争取添加一个本地日志追踪功能。

新版本用了半晚上，没有再出现键盘弹出空白的问题了

**Comment by swh922** [comment]
> 请问新版本还有第一张截图中键盘显示错位和字体较小的问题没？键盘显示的问题是横竖屏切换错乱导致的，新版本应该已经解决，当横屏游戏时会默认切换到悬浮键盘。

分别用新版雨燕、fcitx5和讯飞测试一遍，雨燕和fcitx5显示依旧很小，讯飞正常，如图
![IMG_20240830_003546.jpg](https://github.com/user-attachments/assets/3e2cf432-bbd5-415a-b2a9-615bc196e2c3)
![IMG_20240830_003624.jpg](https://github.com/user-attachments/assets/bca6bb20-42a9-4f7b-9161-64416e3a9da8)
![IMG_20240830_003601.jpg](https://github.com/user-attachments/assets/9b71a24c-6e19-4443-8ee1-73a2189b943a)

**Comment by gurecn** [comment]
我试了一下，微信输入法也是比较小，我仔细看了一下，在未输入任何内容前，输入框里的光标比较小，当输入内容后，讯飞输入法时光标变大了，而其他输入法光标不变。
暂不确定是怎么回事,理论上输入法不会影响其他输入框字体大小的才对。我记录一下这个问题。
