### ISSUE TITLE
关于工具栏显示

### ISSUE THREAD

**Issue by sictyc** [gurecn/YuyanIme#27]
最上面一行能否像小企鹅输入法一样显示工具栏，还有就是希望增加个文本编辑功能，把剪贴板和文本编辑直接显示在工具栏上，这两个是比较常用的功能，或者是可以选择把哪些功能显示在工具栏上就更好了。
![Screenshot_2024-08-28-09-49-12-981_com github android-edit](https://github.com/user-attachments/assets/39c1f0f6-a2e0-4fd9-8802-349c3b21ef28)
![Screenshot_2024-08-28-09-50-40-049_com github android-edit](https://github.com/user-attachments/assets/928d70b8-05a9-43f2-877f-ea658ca051cd)

**Comment by gurecn** [comment]
感谢建议，这两项功能均列入后续计划了。

**Comment by gurecn** [comment]
v20240914.15版本已更新，增加输入法菜单栏功能。邀请您体验。期待您的反馈。
