### ISSUE TITLE
有几点排版方面的建议

### ISSUE THREAD

**Issue by az4399** [gurecn/YuyanIme#28]
1.26字母键盘，现在的**字母**太细了，没有重点，希望可以突出**字母**，**特殊字符**保持细化

2.九宫格的**字母**也希望有稍微加粗的选项，太细了点

3.九宫格左边的**符号选择框**的下面的那两个框体，框的上下大小希望能稍微缩小一点点，平摊给左边的**符号选择框**

另外：
可以加个**捐赠码**
九宫格、不联网、好用的输入法太难找了
我刚用，有待体验，如果用着好用会考虑捐赠

哦对了希望可以导入词库

**Comment by gurecn** [comment]
感谢您的建议，我会考虑在后续版本加入相关优化。
第三个建议没太明白，是指`符号`、`表情`两个按键矮一些，让上面的`常用符号列表`高度长一些吗？
暂不支持捐赠功能哈，您的使用和反馈是对作者最大的鼓励，期待您后续继续使用支持。谢谢

**Comment by az4399** [comment]
第三个建议就是你说的这样，不然下面两个按钮太难看了

**Comment by gurecn** [comment]
第三个建议能举一个例子吗？我测试了一下发现新词打过一次，下次再输入同样的拼音能够记忆的啊

**Comment by az4399** [comment]
![1](https://github.com/user-attachments/assets/d4d9e261-e9e1-4c08-b5a5-88b2f5336b54)
![2](https://github.com/user-attachments/assets/c394a26d-5665-4970-b59f-fafa64e16b56)
可能还是词库的问题？模糊音？
一个是全打出来了woyebuzhidao
另一个是woyebuzhid

**Comment by gurecn** [comment]
您看看是不是输入按键过快丢键了？woyebuzhidao（我也不知道）按键是：96,93,28,944,326。woyebuyige按键是：96,93,28,94,43,他们按键不同，所以不会匹配出同样的候选词的。

**Comment by az4399** [comment]
刚又发现一个不方便的问题，就是26键输入的时候，好像不能取消单词候选模式，比如说我只想输入纯英文字母，在ssh终端输入命令，但是输入法总是有候选单词模式，不能输入纯英文字母，要手动选择，很麻烦，我想有输入一个字母就是一个字母的这种选项
