### ISSUE TITLE
再提个小建议，希望单手模式可以设置默认左手或者加入记忆功能，我是左撇子，打开单手模式都会变成默认右手，每次都需要手动切换一次，如图

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#30]
![IMG_20240828_195555.jpg](https://github.com/user-attachments/assets/410485de-cef0-48b5-9aa5-c16672342066)

**Comment by gurecn** [comment]
今天晚些时候会发布版本，加入该功能。

**Comment by gurecn** [comment]
新版本已加入该功能，期待您的反馈[v20240829.09](https://github.com/gurecn/YuyanIme/releases/tag/v20240829.09)
