### ISSUE TITLE
刚用新版，很nice，再提几个建议

### ISSUE THREAD

**Issue by az4399** [gurecn/YuyanIme#32]
更新了，太nice了

1.
之前我提到的字母字体大小建议，九宫格加粗了，没毛病很清晰，👍

但是我看了下，26英文字母确实加粗了，但是**看起来还是很小**，希望可以修改一下字母的px之类的大小，现在就是框很大，字母的字体大小又很小，不清晰明了

2.
另一个就是英文键盘输入字母的问题，希望加一个选项开关单词联想输入模式，因为我经常用ssh终端，或者termux这种，通常是需要直接输入字母命令的，单词联想就很难用，还需要点一下候选栏的英文字符串
![IMG_20240829_155241](https://github.com/user-attachments/assets/176cfd08-e379-4739-94a1-b8e57f1c5a91)

**Comment by gurecn** [comment]
感谢您的及时反馈，第一个问题下个版本我继续优化。第二个问题，我继续参考一下主流输入法的做法。

**Comment by gurecn** [comment]
v20240914.15版本已更新，增加长按`Shift`按键，开启、关闭英语拼写模式，邀请您尝试，期待您的反馈。
