### ISSUE TITLE
希望可以添加底栏，一边是切换输入法，一边是剪切板

### ISSUE THREAD

**Issue by bandengzex** [gurecn/YuyanIme#33]
类似于小米自带输入法的底栏。之前在同文上是可以实现类似功能的

另外为何我使用时剪切板无法使用呀，权限已经打开了，剪切板打开是空的，也无法粘贴内容

**Comment by gurecn** [comment]
当前看，小米的工具栏只有小米定制输入法可用，不是定制输入法用不了。可以到`手机系统设置`-`更多`-`更多`-`语言与输入法`-`全面屏键盘优化`，选择`默认键盘`关闭。

**Comment by bandengzex** [comment]
> 当前看，小米的工具栏只有小米定制输入法可用，不是定制输入法用不了。可以到`手机系统设置`-`更多`-`更多`-`语言与输入法`-`全面屏键盘优化`，选择`默认键盘`关闭。

不是用小米自带的工具栏，而是通过主题另加一个工具栏，也就是加一个第五排按键，两个按钮

**Comment by gurecn** [comment]
明白您的意思了，就是雨燕输入法自己实现小米手机中`全面屏键盘优化`功能吧？做后续规划时我考虑进去。感谢您的建议

**Comment by bandengzex** [comment]
> 明白您的意思了，就是雨燕输入法自己实现小米手机中`全面屏键盘优化`功能吧？做后续规划时我考虑进去。感谢您的建议

对的，我之前用同文输入法的时候主题能做到，证明rime应该也能
![qq_pic_merged_1724924322081](https://github.com/user-attachments/assets/ea82055e-ea74-4f37-bca6-242b9731879e)

**Comment by swh922** [comment]
> 明白您的意思了，就是雨燕输入法自己实现小米手机中`全面屏键盘优化`功能吧？做后续规划时我考虑进去。感谢您的建议

建议还是学主流输入法在顶部自定义快捷按钮，这样兼容性更好，我是类原生，如图，底部默认左边按钮是关闭输入法，默认右边是切换其它输入法![IMG_20240830_202538.jpg](https://github.com/user-attachments/assets/57bd7bf0-100d-4fab-9d47-06bd5a7b1b2e)

**Comment by gurecn** [comment]
每个人需求不一样，但是大部分人都需要自定义`顶部自定义快捷按钮`，这个功能我会尽快加入。
至于底部`全面屏键盘优化`按钮功能，则不同手机显示不同。有些手机已默认加入该功能，我后续规划使用判断方式，若手机已有系统导航栏的情况下隐藏底部`全面屏键盘优化`按钮，没有系统导航栏时才显示。
感谢你们的反馈。

**Comment by gurecn** [comment]
新版本已增加全面屏键盘优化功能，请下载体验。
