### ISSUE TITLE
希望给悬浮键盘添加可移动功能，像小窗一样，而不是固定位置，固定位置有时候会遮挡输入框

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#34]

**Comment by swh922** [comment]
> 您尝试一下在键盘`悬浮模式`时，点击键盘左上角雨燕图标-选择`键盘调节`，其中上侧`≡`按钮为调节键盘高度，下侧`≡`按钮为调节键盘上下、左右位置。
> 非悬浮模式时，键盘仅支持调节高度及上下位置。

果然可以，这功能深藏不露😄😄

**Comment by YukiRus** [comment]
@gurecn 在平板等大尺寸设备上使用悬浮键盘的时候，移动键盘位置是一个相对比较高频的操作，每次都要点开设置需要三步，稍显麻烦，不知道是否可以学习一下部分商业输入法，将悬浮模式的键盘移动放置在键盘顶部呢？感谢
