### ISSUE TITLE
横屏模式下输入字后不关闭输入法 无法发送信息

### ISSUE THREAD

**Issue by QingMoLianQu** [gurecn/YuyanIme#35]

**Comment by QingMoLianQu** [comment]
测试了一下竖屏，竖屏有时候会卡输入法![IMG_20240830_101307.jpg](https://github.com/user-attachments/assets/236ad331-a457-4eb9-a562-247f480706dd)

按这个关闭不了
横屏是不关闭这个，就不能发送信息

**Comment by gurecn** [comment]
竖屏有时候会卡输入法，按这个关闭不了
> 是指`竖屏模式`时，点击截图中红色圈住的`向下箭头`不会收起键盘还是收起时卡顿？

横屏不关闭键盘无法发送消息的问题我复线出来了，下个版本修复该问题。

**Comment by QingMoLianQu** [comment]
> 竖屏有时候会卡输入法，按这个关闭不了
> > 是指`竖屏模式`时，点击截图中红色圈住的`向下箭头`不会收起键盘还是收起时卡顿？
> 
> 横屏不关闭键盘无法发送消息的问题我复线出来了，下个版本修复该问题。
竖屏的有时候会卡，有时候不会，很难找

**Comment by QingMoLianQu** [comment]
> 竖屏有时候会卡输入法，按这个关闭不了
> 
> > 是指`竖屏模式`时，点击截图中红色圈住的`向下箭头`不会收起键盘还是收起时卡顿？
> 
> 横屏不关闭键盘无法发送消息的问题我复线出来了，下个版本修复该问题。

竖屏的不太好触发，不知道怎么回事

**Comment by gurecn** [comment]
好的，下个版本我将触控区域放大一些，感谢您的反馈。
