### ISSUE TITLE
键盘默认字体换了？

### ISSUE THREAD

**Issue by zhl111** [gurecn/YuyanIme#37]
打开设置后点左上角的回退键没有反应…这键盘字体没有以前的纤细感轻盈感了

另：中文的省略号是六个点……，英文的是三个点…

**Comment by gurecn** [comment]
1. 打开设置后点左上角的回退键没有反应
> 该问题在您手机上必现吗？有什么规律没？
2. 这键盘字体没有以前的纤细感轻盈感了
> 对，其他用户建议及借鉴其他输入法，字体加粗加大了。您手机显示效果不理想吗？难以接受的话，后续我可以在键盘主题中添加调整字体大小选项。
3. 中文的省略号是六个点……，英文的是三个点…
> 这个我确实没注意，下个版本我加一下。

**Comment by gurecn** [comment]
[雨燕输入法v20240907.08](https://github.com/gurecn/YuyanIme/releases/tag/v20240907.08)已修复回退键和符号的问题。感谢您的反馈，请您体验。

**Comment by gurecn** [comment]
最新版本v20240914.15版本已增加字体粗体开关，请下载体验，期待您的反馈。
