### ISSUE TITLE
请求添加点击候选词震动功能

### ISSUE THREAD

**Issue by laurenafolk** [gurecn/YuyanIme#39]
感谢大佬做出好用的输入法，有个问题是点击候选词没有震动，这样影响手感 😄 如果能加个开关啥的 就更好了 感谢。
另一个就是键盘左侧雨燕图标和右边的收起键盘按钮能否再小一点。似乎昨天新版的图表比以前小了一点？

**Comment by gurecn** [comment]
可以的，这两个优化点我下周版本争取加上，感谢您的反馈。
