### ISSUE TITLE
bug：上滑输入符号失效

### ISSUE THREAD

**Issue by glxhenan** [gurecn/YuyanIme#40]
bug反馈：ColorOS 14系统，最新版本雨燕输入法，不能上滑输入符号。

另：
1、建议增加工具栏；
2、有些字打不出来，比如“灺”

**Comment by swh922** [comment]
我类原生也发现这个bug，上滑符号无效

**Comment by gurecn** [comment]
1.暂时没有上滑符号输入功能。当前长按触发时间可以在`设置-键盘-键盘-按键长按灵敏度进行调整。上滑输入功能已经列入计划，请等待后续版本加入。

2.建议增加工具栏；
> 该功能也已经列入计划，请等待后续版本加入。

3.字库缺失问题我会将问题反馈给`白霜词库`，由词库进行扩充，我会及时更新。
感谢您们的建议与反馈。

**Comment by glxhenan** [comment]
> 1.暂时没有上滑符号输入功能。当前长按触发时间可以在`设置-键盘-键盘-按键长按灵敏度进行调整。上滑输入功能已经列入计划，请等待后续版本加入。
> 
> 2.建议增加工具栏；
> 
> > 该功能也已经列入计划，请等待后续版本加入。
> 
> 3.字库缺失问题我会将问题反馈给`白霜词库`，由词库进行扩充，我会及时更新。 感谢您们的建议与反馈。

这个上滑符号不是上滑输入吗？
![Screenshot_2024-08-31-14-33-20-08_7e737077aeef3f375ee83df1e80d0ecc](https://github.com/user-attachments/assets/04102094-d04e-4e81-a0d7-ca673ccc4c30)

**Comment by gurecn** [comment]
这个不是的，这个当前是长按，不支持上划的。确实描述有问题。上划功能我尽快加一下。感谢您的反馈

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已增加上滑输入符号功能，邀请您的体验，期待您的反馈。
