### ISSUE TITLE
剪切板有时候失效，明明复制了，但是剪切板里没有，必须强制停止再启动，才能正常使用

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#42]

**Comment by laurenafolk** [comment]
出现了同样的bug

**Comment by gurecn** [comment]
已经复现了并解决，请等待下个版本。感谢你们的支持。

**Comment by gurecn** [comment]
[雨燕输入法v20240907.08](https://github.com/gurecn/YuyanIme/releases/tag/v20240907.08)已修复该问题。感谢您的反馈，请您体验。
