### ISSUE TITLE
生僻字如丿无法输入

### ISSUE THREAD

**Issue by iminto** [gurecn/YuyanIme#43]
比如 丿(pie)，丨 (gun)等等，f4a里面是可以输入的

**Comment by gurecn** [comment]
当前词库没有引入生僻字词库，词库越大，输入卡顿越严重，特别是九键。这个刚需的话，后续可以增加扩展生僻字开关。

**Comment by gurecn** [comment]
新版本已增加大字表支持，请下载使用新版本。感谢您的支持
