### ISSUE TITLE
请求重新设计APP图标

### ISSUE THREAD

**Issue by VillagerTom** [gurecn/YuyanIme#44]
![IMG_20240902_214012.JPG](https://github.com/user-attachments/assets/52d461de-3aeb-4039-84d0-0b4885f9ff85)

**Comment by VillagerTom** [comment]
> ![IMG_20240902_214012.JPG](https://github.com/user-attachments/assets/52d461de-3aeb-4039-84d0-0b4885f9ff85)
> 
> 

图标与迅雷雷同，其形象更像是一只蜂鸟而不是雨燕。

**Comment by gurecn** [comment]
好吧，这个我倒是没注意😅

**Comment by VillagerTom** [comment]
请求重新设计APP图标以符合“雨燕”形象。

**Comment by gurecn** [comment]
感谢建议，我会考虑的，当前主要在功能优化上，功能逐渐完善后我着手设计一下。
