### ISSUE TITLE
用scrcpy连接手机，使用外接键盘时的bug

### ISSUE THREAD

**Issue by chinagaofeng** [gurecn/YuyanIme#45]
bug1：外接键盘所敲字幕会自动上屏
bug2：想删掉这些自动上屏的字母，用键盘左右键移光标时会每次跳2个字母

**Comment by gurecn** [comment]
物理键盘暂时还没有优化，中间可能需一个版本迭代，请关注更新内容。

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)
