### ISSUE TITLE
又更新了👍，再来几点建议

### ISSUE THREAD

**Issue by az4399** [gurecn/YuyanIme#46]
之前提到的字母字体大小问题很清晰明了了，纯字母输入模式也有了

👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

再来几个建议

1. 九宫格输入里，输入后希望还是**默认显示拼音**，而不是数字,因为有时候会打错，如果打错了，一样就能看出来拼音错了

![IMG_20240907_104741](https://github.com/user-attachments/assets/9094d111-5aee-4621-a464-13aa88030045)

2. 还有一个就是模糊音的问题，应该是叫模糊音吧？或者是词库的问题？

    举个例子就是输入“**你不知道**”,全拼出来是“nibuzhidao”，数字应该是“64,28,944,326"

    希望只输入“nibuzhid"，数字应该是“64,28,944,3"，就能打出来，**但是实测被识别成了"64,28,94,43"**

**Comment by gurecn** [comment]
咦，您的拼音栏怎么会显示数字？正常应该是拼音才对，我用多个手机都没有复现出来怎么显示数字😭。
第二个问题，拼音栏显示的拼音其实就是第一个候选词的拼音取已输入的部分，您手机上显示的是数字，所以看着不对。
我用自己手机测试，输入“64,28,944,3"，拼音栏显示的是“mi`bu`yi`ge”(弥补一个)，和"64,28,94,43"是对应的。
至于手机为什么显示数字，需要我分析一下代码看看了。

**Comment by az4399** [comment]
> 咦，您的拼音栏怎么会显示数字？正常应该是拼音才对，我用多个手机都没有复现出来怎么显示数字😭。 第二个问题，拼音栏显示的拼音其实就是第一个候选词的拼音取已输入的部分，您手机上显示的是数字，所以看着不对。 我用自己手机测试，输入“64,28,944,3"，拼音栏显示的是“mi`bu`yi`ge”(弥补一个)，和"64,28,94,43"是对应的。 至于手机为什么显示数字，需要我分析一下代码看看了。

我打错了，是96/93/28/944/3，结果是  我也不一个

**Comment by laurenafolk** [comment]
0907.08full版本 出现了为数字不是拼音 同第一个问题

**Comment by gurecn** [comment]
好的，下个版本我强制设定一下显示字母。感谢反馈

**Comment by gurecn** [comment]
最新版本v20240914.15版本已修复，请下载尝试，期待您的反馈。
