### ISSUE TITLE
建议像讯飞输入法那样增加顶栏左右滑动选词，有时候顶栏最右边露出半个字或者词语正好是需要选的，点击不够方便，也需要下拉选词，如图

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#47]
![IMG_20240907_114257.jpg](https://github.com/user-attachments/assets/f020426c-83b8-4266-a57f-1ea32f430942)

**Comment by gurecn** [comment]
这个可以。如果前10个词里有命中时，可以在候选词栏选择，如果命中词在后面，还是希望在候选词界面选择。后期我设置成候选词栏最长加载10个，当超出边界时支持滑动。

**Comment by gurecn** [comment]
这个可以。如果前10个词里有命中时，可以在候选词栏选择，如果命中词在后面，还是希望在候选词界面选择。后期我设置成候选词栏最长加载10个，当超出边界时支持滑动。

**Comment by gurecn** [comment]
最新版本v20240914.15版本已增加该动能，请下载体验，期待您的反馈。
