### ISSUE TITLE
功能及操作方式优化建议

### ISSUE THREAD

**Issue by ZARD1434** [gurecn/YuyanIme#48]
①数字栏完全可以抛弃改成可编辑自定义的功能栏，开始键入数字可以考虑上滑输入
②空格移动光标目前还不够精确，也建议像其他输入法一样做一个独立的光标移动按键，可以放置在功能栏上
③在中文输入状态中，快速键入字母会自动加空格，在输入账号密码的时候会比较麻烦。比如说我在网页上想输入我的账号密码例如“阿布qwer”,会变成“阿布q w er”
④表情键可以跟符号键并在一起，如果你做功能栏的话，那么表情键可以移到功能栏上面去，简洁又方便

**Comment by gurecn** [comment]
感谢您的反馈，124已经在做了，会在后续版本逐渐加入。
第三个问题能详细描述一下吗？您是通过九宫格还是全键盘输入中文，然后通过长按案件输入的字母吗？我没有复现出来这个问题。
期待您的反馈。

**Comment by ZARD1434** [comment]
> 感谢您的反馈，124已经在做了，会在后续版本逐渐加入。
> 第三个问题能详细描述一下吗？您是通过九宫格还是全键盘输入中文，然后通过长按案件输入的字母吗？我没有复现出来这个问题。
> 期待您的反馈。

是中文全键盘模式下，使用回车键键入英文字母会自动加空格（q w er t yuiop），在需要汉字跟字母穿插输入的场景下显得异常繁琐，因为我需要来回按 【中/英】 切换键😂

**Comment by swh922** [comment]
> 感谢您的反馈，124已经在做了，会在后续版本逐渐加入。
> 第三个问题能详细描述一下吗？您是通过九宫格还是全键盘输入中文，然后通过长按案件输入的字母吗？我没有复现出来这个问题。
> 期待您的反馈。
顶部数字栏确实没必要，键小且容易误触，可以参考一些主流输入法，比如讯飞，26键最上面一行上滑输入数字，9键上滑输入数字，可以免去切换数字键盘，混输可以明显提升效率，并且不用改变原有按键布局，如图
![IMG_20240907_180712.jpg](https://github.com/user-attachments/assets/89584225-9313-4709-815f-5c834672fe09)

**Comment by kiwiXZRO** [comment]
> > 感谢您的反馈，124已经在做了，会在后续版本逐渐加入。
> > 第三个问题能详细描述一下吗？您是通过九宫格还是全键盘输入中文，然后通过长按案件输入的字母吗？我没有复现出来这个问题。
> > 期待您的反馈。
> 
> 顶部数字栏确实没必要，键小且容易误触，可以参考一些主流输入法，比如讯飞，26键最上面一行上滑输入数字，9键上滑输入数字，可以免去切换数字键盘，混输可以明显提升效率，并且不用改变原有按键布局，如图 ![IMG_20240907_180712.jpg](https://private-user-images.githubusercontent.com/23072078/365359945-89584225-9313-4709-815f-5c834672fe09.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MzUwNzQsIm5iZiI6MTcyNTczNDc3NCwicGF0aCI6Ii8yMzA3MjA3OC8zNjUzNTk5NDUtODk1ODQyMjUtOTMxMy00NzA5LTgxNWYtNWM4MzQ2NzJmZTA5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDE4NDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Y2RjYzI2MzZlNDFlZTg4ZmUxNTRkNGMzZWE4MWU2ZmM5MmIyMDkwYmY4MTZmYjJmZmE0NTU2YzE2MDY3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wcY9UA8qibuG3Rie1ubX08tRHbboh_3GTZQQt8QS0A)

认为数学栏有必要，我经常使用它；如果你认为没必要可以关闭展示，而且你提出的数字内嵌输入效率并不高。

**Comment by kiwiXZRO** [comment]
我认为数学栏有必要，我经常使用它。如果你认为没必要可以关闭展示，而且你提出的数字内嵌输入效率并不高。

**Comment by kiwiXZRO** [comment]
我认为数学栏有必要，而且是我认为目前最好用的数字栏的输入法，我经常需要使用中文与数字，这样避免频繁切换全键盘与九宫格的步骤，提升效率。你提出的取消数字栏我是不赞同的，当然也希望开发者新增“数字键”提供多一种选择，但我也希望保留目前数字栏的布局至少对从事的行业很有帮助。

**Comment by gurecn** [comment]
是中文全键盘模式下，使用回车键键入英文字母会自动加空格（q w er t yuiop），在需要汉字跟字母穿插输入的场景下显得异常繁琐，因为我需要来回按 【中/英】 切换键😂
> 这个问题已复现，下个版本修复。
其他建议我也收到了，我会尽量满足大家的需求，会尽可能便捷的增加一些人性化设置项满足不同诉求。
再次感谢大家的反馈。

**Comment by gurecn** [comment]
1、3、4问题已修复，请下载最新版本v20240914.15版本体验，期待你们的反馈

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已修复以上相关问题，邀请您的体验，期待您的反馈。
