### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#49]
英文键盘如果随便乱输入几个非英文单词字母，比如yuyan，候选栏空白，无可选词，这种情况下切换中文输入法，再输入中文，输入框里原本的yuyan会消失，我用讯飞测试同样的情况，候选栏会有yuyan可选择，即便不选择候选栏里的yuyan，在这种情况下切换中文后，输入框里的yuyan也会由待选变确定，如图
![IMG_20240909_023449.jpg](https://github.com/user-attachments/assets/55513382-ad7c-4cf0-931d-7e6bc37a1fbc)

![IMG_20240909_023257.jpg](https://github.com/user-attachments/assets/9feb8c14-d8a8-4302-8749-255ff8387ab7)

**Comment by gurecn** [comment]
明白，这是本次更新词库时覆盖了方案导致功能回退，上个版本不存在该问题。下个版本我会再加上的。感谢反馈。

**Comment by gurecn** [comment]
v20240914.15版本已修复该问题，请下载体验，期待您的反馈。

**Comment by swh922** [comment]
> v20240914.15版本已修复该问题，请下载体验，期待您的反馈。

感谢作者，我发现关闭英文单词补全，就可以随便输入英文字母了，当打开英文单词补全的时候，非字库英文单词的英文依旧无法输入

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已增加英文补全快速开关（长按Shift选择开启直输、拼写模式），邀请您的体验，期待您的反馈。
