### ISSUE TITLE
在 切换键盘 选项中 我没有发现 简拼？

### ISSUE THREAD

**Issue by jujubeja** [gurecn/YuyanIme#5]
在 雨燕输入法  切换键盘 选项中 我没有发现 简拼？

> 什么是简拼模式？如何使用简拼？
Google 输入法支持简拼输入，如输入"wlj"可以得到"王老吉"。另外，为了满足网络缩写的需要，Google 输入法也支持zh,ch,shi 声母简拼。例如：你想输入"实时查询" 你只要输入"ssry"或者"shshry"都可以输入"事事如意"。如果您希望使用此功能，请点击状态栏上的"设置"按钮，选择"属性设置" > "拼音模式",选中"简写时使用"z,c,s"代表"zh,ch,sh"，以启用此功能。同时，Google 输入法也支持简拼全拼的混合输入，例如：输入"srf""sruf""shrfa"都可以得到"输入法"。 pinyin_62660_cn.gif 请注意：在这里，声母首字母简拼的作用和模糊音中的"z，s，c"相同。但是，这属于两个不同的功能。即使您没有选择设置里的模糊音，你同样可以用"zly" 输入"张靓颖"。有效使用声母首字母简拼可以提高输入效率，减少误打。例如，要输入"转瞬即逝"几个字，如果您输入传统的声母简拼，必须输入 "zhshjsh"，这样您需要输入 3 个包括"h"的声母,很容易造成输入错误。而如果采用简拼模式，则只需输入"zsjs"就可以了。

**Comment by gurecn** [comment]
当前项目使用薄荷拼音方案，薄荷方案中暂未配置九键简拼。之前开启过，但薄荷词库太大，九宫格方案重码率高，导致简拼输入出现明显卡顿。
确实存在该需求，后续根据情况优化，现版本仅支持全拼。

**Comment by gurecn** [comment]
v4.2.0版本已加入简拼方案，当前默认开启，暂不支持手动开关。参考： [v4.2.0版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.2.0)

**Comment by gurecn** [comment]
>  26键简拼 可以避免重码率高

26键简拼功能一直是支持的。
