### ISSUE TITLE
微软双拼

### ISSUE THREAD

**Issue by Albert2111** [gurecn/YuyanIme#50]
微软双拼输入韵母ing绑在哪个按键，没试到😂

**Comment by gurecn** [comment]
好吧，我漏掉了。我才发现有些双拼是需要使用`;`按键的，下个版本修复该问题。

**Comment by gurecn** [comment]
v20240914.15版本已修复该问题，请下载体验，期待您的反馈。

**Comment by Albert2111** [comment]
已试用，目前没有发现什么问题
