### ISSUE TITLE
作者有群吗，可以建一个群交流。

### ISSUE THREAD

**Issue by 751496032** [gurecn/YuyanIme#55]

**Comment by gurecn** [comment]
当前还未建有交流群，当前产品还不成熟，在完善中，交流群会覆盖有效反馈。
使用上的问题可以在Issues或应用-设置-吐槽与反馈中反馈，我会及时关注并回复。
感谢您的支持。

**Comment by i0799** [comment]
为什么一个输入法切换键都没有？

**Comment by gurecn** [comment]
@i0799 v20240914.15版本已增加输入法切换按键，请下载体验，期待您的反馈。
