### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by YukiRus** [gurecn/YuyanIme#57]
目前输入法在按键的按下-滑动操作上似乎有些欠缺，例如
- 按下退格键往左滑清空已输入内容。
- 字母键上滑输入 大写/对应字符数字 （目前是长按后上滑或者上滑后长按可以触发，可以设置为上滑马上松开将输入字母上面显示的那个字符，长按后才弹出选框选择要大写还是小写，现在这个体感上稍微有些不顺畅）
这样感觉会比长按来的流畅一些？
[以及在其他issue里提到过的悬浮键盘在大尺寸设备上移动位置操作麻烦的问题](https://github.com/gurecn/YuyanIme/issues/34#issuecomment-2346010789)

其实也是被国产的输入法养成了习惯，不知道实现起来是否麻烦

顺便夸夸，这个应该是我见过最好看的rimeandroid输入法了，很喜欢，感谢作者的付出

**Comment by gurecn** [comment]
感谢您的反馈，您提供的两个建议均是在开发功能，但不确定具体在哪个版本能够加入，后续请关注版本发布说明。

**Comment by gurecn** [comment]
关于[以及在其他issue里提到过的悬浮键盘在大尺寸设备上移动位置操作麻烦的问题](https://github.com/gurecn/YuyanIme/issues/34#issuecomment-2346010789)，是我没关注漏掉了，我想问一下您会频繁移动键盘位置吗？

**Comment by YukiRus** [comment]
> 关于[以及在其他issue里提到过的悬浮键盘在大尺寸设备上移动位置操作麻烦的问题](https://github.com/gurecn/YuyanIme/issues/34#issuecomment-2346010789)，是我没关注漏掉了，我想问一下您会频繁移动键盘位置吗？

如果在手机我基本上不使用悬浮键盘，但在平板上是需要的，毕竟平板不适合固定键盘，但悬浮键盘需要挪开看被遮住的东西

**Comment by YukiRus** [comment]
还有一个是26键的长按字符，如果在qwer行上放123456的话感觉会更合适？这样比单独的数字行更省空间一点。当然这是我的个人习惯，不太清楚别人是什么习惯，仅供参考哈

**Comment by gurecn** [comment]
明白了，我会将移动条在悬浮键盘时显示出来。
关于输入数字符号的功能，后续也会支持设置为主流方式，在qwer行上划数字。

**Comment by YukiRus** [comment]
> 明白了，我会将移动条在悬浮键盘时显示出来。 关于输入数字符号的功能，后续也会支持设置为主流方式，在qwer行上划数字。

嗯嗯，感谢哈

**Comment by gurecn** [comment]
v20240914.15版本已增加悬浮键盘移动条，请下载体验，期待您的反馈。

**Comment by YukiRus** [comment]
> v20240914.15版本已增加悬浮键盘移动条，请下载体验，期待您的反馈。

非常完美，点赞

**Comment by YukiRus** [comment]
一个小问题，就是在悬浮键盘模式下 切换输入法的图标会变形 压扁了。不影响使用，但不好看，可以处理一下看看 @gurecn
