### ISSUE TITLE
符号: 删除和 英语符号 相同的 中文符号

### ISSUE THREAD

**Issue by jujubeja** [gurecn/YuyanIme#59]
可能这是一个无礼的请求, 但是 如果你在手机上编写的代码 很容易不小心打成 中文符号。
或者符号面板把 英语符号 放在 中文符号 前面

**Comment by gurecn** [comment]
能具体描述一下在那个界面输入吗？
我理解应该不会出现这种情况才对，若是您用英文键盘，点击符号时弹出英文符号界面，不会弹到中文符号界面才对。长按选择符号时，符号都有标注是否是半角。且当英文键盘时，默认选择的是半角符号。

**Comment by gurecn** [comment]
能具体描述一下在那个界面输入吗？
我理解应该不会出现这种情况才对，若是您用英文键盘，点击符号时弹出英文符号界面，不会弹到中文符号界面才对。长按选择符号时，符号都有标注是否是半角。且当英文键盘时，默认选择的是半角符号。

**Comment by gurecn** [comment]
能具体描述一下在那个界面输入吗？
我理解应该不会出现这种情况才对，若是您用英文键盘，点击符号时弹出英文符号界面，不会弹到中文符号界面才对。长按选择符号时，符号都有标注是否是半角。且当英文键盘时，默认选择的是半角符号。

**Comment by gurecn** [comment]
好的，再询问一下，您习惯在中文模式下使用英文符号吗？

**Comment by gurecn** [comment]
好的，明白了
