### ISSUE TITLE
可否把内置词库更换为白霜拼音？

### ISSUE THREAD

**Issue by gaboolic** [gurecn/YuyanIme#6]
白霜拼音链接：https://github.com/gaboolic/rime-frost
作者可以体验下

**Comment by gurecn** [comment]
好，我体验一下，可以的话后面我可以内置进去供选择

**Comment by gurecn** [comment]
最新的[v4.3.3版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.3.3)已经内置白霜词库，邀请您体验，期待您的反馈。

**Comment by gaboolic** [comment]
看到了 我已经在https://github.com/gaboolic/rime-frost加了雨燕输入法的友情链接

**Comment by gaboolic** [comment]
> 看到了 我已经在https://github.com/gaboolic/rime-frost 加了雨燕输入法的友情链接

**Comment by gaboolic** [comment]
后面和你沟通下 双拼加形的事情，可以做到任意双拼任意辅助码任意排列组合，并且是支持直接辅助码的
