### ISSUE TITLE
越来越好用了，再提几个建议

### ISSUE THREAD

**Issue by az4399** [gurecn/YuyanIme#63]
1.就是关于剪切板的问题，现在语燕**在非输入状态下**复制的内容，再次输入的时候**可以**显示在工具栏，因为我一直是使用kde connect与手机共享剪切板，所以希望可以**在输入状态下**也能**实时地**将后台复制的内容显示在工具栏那一条，点一下就可以粘贴

2.就是输入法**收起来**的那个按钮，能不能改成普通的>向下的这种形式，现在的箭头感觉好别扭

3.感觉工具栏横条那一块的上下宽度，还可以再窄一丢丢，现在的上下宽度好像稍微有点宽

4.希望加入模糊音学习功能，将常输入的单词或者句子，进行模糊音的学习，比如说九宫格输入一次：**3(DEF)**，语燕一直都是默认输入：**E**，然后就被识别成了：**额**，其实我想输入的是：**的**，这个好像也无法学习到，每次都要输入两次：**3(DEF)** **3(DEF)**，才能出现：**的**，太不方便了

**Comment by gurecn** [comment]
收到，这几个问题我会尽快完善。感谢支持。
