### ISSUE TITLE
关于中文九键UI界面的一点小建议

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#65]
作者辛苦了，建议增加数字0，其它数字都可以通过长按输入，唯独0必须通过切换数字键盘才能输入，建议参考国内一些输入法，把@移到左边快捷符号栏，用0取代@的位置，如图
![1726305776789.jpg](https://github.com/user-attachments/assets/df1fe08f-3f9d-4252-bceb-2d30393313ac)
也有一些输入法，比如gboard是通过长按空格键输入0，但是咱这边长按变成移动光标，我猜可能会有冲突，如图
![Screenshot_20240914-173416_Alpha Launcher.png](https://github.com/user-attachments/assets/d33604aa-409d-4007-9d4a-fc9235cdd627)
希望九键界面以后加入左边常用快捷符号自定义，因为每个人常用的符号频率习惯是不一样的

**Comment by gurecn** [comment]
感谢建议，我会继续优化键盘布局。
当前九宫模式下确实漏掉了0键，一个折中方案可以长按`123`按键，此时默认选中熟悉0。

**Comment by swh922** [comment]
> 感谢建议，我会继续优化键盘布局。
> 当前九宫模式下确实漏掉了0键，一个折中方案可以长按`123`按键，此时默认选中熟悉0。

感谢提醒，刚发现长按123默认是0，讯飞和搜狗都是把0放到@位置，如图↴
![Screenshot_20240916-105933_Alpha Launcher.png](https://github.com/user-attachments/assets/c2fa6ef3-39a5-4893-9673-1c6a2b53c38a)

![273d7f56814c6d5bbe7e3e6cc0bd637a.png](https://github.com/user-attachments/assets/3abecaae-8c59-47de-9748-45e91068a110)

微信输入法和谷歌输入法则是放到空格键，如图↴
![16887d0aa745faa3b55504aed0bf56cc.jpeg](https://github.com/user-attachments/assets/875c4c1d-ff5d-4bdb-9902-3ab24db51c6b)

![Screenshot_20240916-111243_GitHub.png](https://github.com/user-attachments/assets/68d04c83-218b-49a1-9b0c-ef3c7b4d0ac6)
以上几种都可以借鉴一下，对于不熟悉的人也可以一目了然，另外，我发现@键长按和符号键长按基本是一样的，功能有些重复了，还有就是之前说的，右边竖型符号栏，希望可以考虑添加自定义调整，以适应不同用户的使用习惯
以上建议仅供参考，具体还以作者的调整为准，再次感谢作者大大的辛苦付出，希望可以在关于里添加二维码，让用户自由打赏

**Comment by gurecn** [comment]
收到您的建议，后续我会尽量满足主流用户的习惯，暂时规划的提供类似讯飞一样的配置项，让用户选择搜狗，百度，讯飞等不同键盘类型。
你们能认真体验并反馈我已经很高兴了，暂时不用打赏哈。

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已优化相关功能，邀请您的体验，期待您的反馈。
快捷符号自定义功能我已记录，会尽快加入。
