### ISSUE TITLE
又发现一个bug

### ISSUE THREAD

**Issue by az4399** [gurecn/YuyanIme#68]
九宫格输入，然后滑动候选词去选后面的词，然后再次输入的时候，候选词滑动的位置不会归位，还是上一次滑到的地方

**Comment by gurecn** [comment]
收到，下个版本会修复该问题。感谢反馈。

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已修复该问题，邀请您的体验，期待您的反馈。
