### ISSUE TITLE
又发现一个小bug

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#71]
菜单里面打开繁体按钮，但是顶部的繁体快捷按钮显示未打开
![Screenshot_20240916-191205_PiTT.png](https://github.com/user-attachments/assets/80b3991c-a4d8-4358-8168-aeee6f28edb4)

另外之前反馈的在打开英文单词补全的情况下，非英文单词（比如yuyan）仍然不能选中输入，关闭英文单词补全则可以，别家的输入法是，开启英文单词补全的情况下，依然可以输入非单词英文，具体如图
![IMG_20240916_191820.jpg](https://github.com/user-attachments/assets/0ba3a748-a22d-449e-9fd5-93c96d9bc560)
![IMG_20240916_192133.jpg](https://github.com/user-attachments/assets/9fac8182-a6f5-45a9-b867-1c9ebb7bdbf3)
![IMG_20240916_192827.jpg](https://github.com/user-attachments/assets/0509b906-139e-47cd-abaf-4ff571755316)

**Comment by gurecn** [comment]
第一个问题我复现出来了，下个版本修复。
第二个问题我没有复现，我怀疑是您直接覆盖安装的问题，您能否卸载重新安装一下试试？
![Screenshot_2024-09-16-19-54-53-435_com miui notes](https://github.com/user-attachments/assets/da45ce13-1760-434b-b831-5515757dabf2)
![Uploading Screenshot_2024-09-16-19-54-53-435_com.miui.notes.jpg…]()

**Comment by swh922** [comment]
> 第一个问题我复现出来了，下个版本修复。
> 第二个问题我没有复现，我怀疑是您直接覆盖安装的问题，您能否卸载重新安装一下试试？
> ![Screenshot_2024-09-16-19-54-53-435_com miui notes](https://github.com/user-attachments/assets/da45ce13-1760-434b-b831-5515757dabf2)
> ![Uploading Screenshot_2024-09-16-19-54-53-435_com.miui.notes.jpg…]()
> 

确实覆盖安装的，清除数据再测试后好了
