### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#72]
登录账号，光标切换到密码栏的时候，键盘还停留在上一个状态（比如数字或中文），主流输入法的做法是，当光标切换到密码栏的时候，键盘自动切换到英文模式，因为绝大部分密码都是字母和数字组合，我测试了讯飞、谷歌和小企鹅，光标切到密码栏的时候，都是自动切换到英文键盘，希望雨燕也跟进这个功能
![IMG_20240917_080710.jpg](https://github.com/user-attachments/assets/b62313b8-5be7-4be2-8ec7-813230f33c73)

**Comment by gurecn** [comment]
感谢建议，我测试一下相关问题，会在下个版本优化相关功能。

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已增加相关功能，邀请您的体验，期待您的反馈。

**Comment by swh922** [comment]
> 最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已增加相关功能，邀请您的体验，期待您的反馈。

感谢大佬，已下载使用，语燕作为主力输入法，越来越完善了，再提个小建议，我发现乱序17键盘的一些上滑符号是英文符号，比如冒号、问号和叹号，希望后面能调整一下改成中文符号
另外，我经常使用繁体，“爲”的异体字“為”这个字在港台使用频率远胜前者，现在语燕还是打不出来
