### ISSUE TITLE
刚刚下载试了，发现几个问题。

### ISSUE THREAD

**Issue by yhx0022** [gurecn/YuyanIme#73]
第一，键盘上没有逗号，句号这些常用的键位。而且只能长按才能输入符号，不能下划或上划输入符号。

第二，振动应该不是调用我手机上本来的振动。感觉振动很松散。

第三，删除键不好用。一不小心长按就把辛苦打出来的字全删了。
希望能参考小企鹅的删除方式，手指抬起不再按住删除键时，才触发删除。

**Comment by yhx0022** [comment]
第一，键盘上没有逗号，句号这些常用的键位。而且只能长按才能输入符号，不能下划或上划输入符号。

第二，振动应该不是调用我手机上本来的振动。感觉振动很松散。

第三，删除键不好用。一不小心长按就把辛苦打出来的字全删了。
希望能参考小企鹅的删除方式，手指抬起不再按住删除键时，才触发删除。

**Comment by gurecn** [comment]
第一，键盘上没有逗号，句号这些常用的键位。而且只能长按才能输入符号，不能下划或上划输入符号。
> 后续版本会提供常规键盘模式，和主流键盘保持一致。当前可使用长按选择或长按`符号`按键输入。

第二，振动应该不是调用我手机上本来的振动。感觉振动很松散。
> 当前主流手机不支持应用调节震动强度，雨燕输入法调节强度采用调整震动时长来实现，选择系统默认强度时，使用的时系统强度。

第三，删除键不好用。一不小心长按就把辛苦打出来的字全删了。
> 确实发现雨燕输入法触发按键操作是在按键按下，其他输入法是在按键抬起，这个下个版本我修复。
感谢您的反馈。

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已修复相关问题，邀请您的体验，期待您的反馈。

**Comment by TTTPOB** [comment]
> >第二，振动应该不是调用我手机上本来的振动。感觉振动很松散。
> 
> 当前主流手机不支持应用调节震动强度，雨燕输入法调节强度采用调整震动时长来实现，选择系统默认强度时，使用的时系统强度。

这个震动问题应该是因为线性马达调用的api跟普通震动不一样吧？我在小米手机上使用同文输入法也是遇到类似的问题，感觉调用的不是线性马达。附上当时我看到的issue链接
https://github.com/osfans/trime/issues/514
