### ISSUE TITLE
又发现一个bug

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#76]
由于横屏挪动悬浮键盘有记忆功能，当竖屏开启悬浮键盘后，导致有可能显示不全，如图
![IMG_20240919_173702.jpg](https://github.com/user-attachments/assets/c7d091cd-1f1d-45a0-a8f0-bacbe29a666e)

![IMG_20240919_173841.jpg](https://github.com/user-attachments/assets/d5650521-09f8-4fe2-ad92-2d12c5c1800e)

以上是横屏悬浮挪到中间改回竖屏后开启悬浮的情况，如果横屏时悬浮键盘挪到左边，改回竖屏再开启悬浮键盘，键盘则直接跑到屏幕外面去了，希望横竖屏对悬浮键盘位置采用各自独立的记忆功能

**Comment by gurecn** [comment]
收到反馈，该问题已复现。因为本周工作比较忙，下周发布版本修复该问题。
感谢您的反馈和支持。

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已修复该问题，邀请您的体验，期待您的反馈。
