### ISSUE TITLE
建议加入计算功能

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#78]
现在国内主流输入法都加入简单的计算功能了，这个功能还是很实用的，希望语燕后期能够跟进，如图
![IMG_20240921_174455.jpg](https://github.com/user-attachments/assets/40b8dea6-6562-40b2-87ee-a211939e8c60)

**Comment by VeleSila** [comment]
还是做纯粹的输入法吧。这本身也不是Rime的功能，别教唆作者去搞什么大而全。

**Comment by swh922** [comment]
> 还是做纯粹的输入法吧。这本身也不是Rime的功能，别教唆作者去搞什么大而全。

我给身边朋友推荐语燕，他希望有这个功能，我就替他建议一下，我自己无所谓有没有

**Comment by gurecn** [comment]
我试了一下其他输入法，确实很多有类似功能，后续我考虑进去。感谢你们的建议

**Comment by gurecn** [comment]
新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)

**Comment by swh922** [comment]
> 新版本已修复该功能，请在新版本下载体验。[v20241230.12](https://github.com/gurecn/YuyanIme/releases/tag/v20241230.12)

最新版（20251222.16）计算功能没有了，希望下个版本加入，叩谢🙏
