### ISSUE TITLE
有考虑基于 KMP 开发PC端吗

### ISSUE THREAD

**Issue by Soltus** [gurecn/YuyanIme#8]
RIME小白, 体验了一下雨燕输入法很喜欢. 在 windows 上我安装了小狼毫但是重新部署一直显示维护中, 而且UI不够现代化, 希望可以在 windows 上使用雨燕

**Comment by gurecn** [comment]
您的喜欢我很荣幸，谢谢您。因为安卓版本还在完善中，暂无精力去开发Windows端了。Windows和移动端不同，Windows输入使用物理键盘，不需要软键盘设计，因此各家输入法都差不多。
