### ISSUE TITLE
手写输入不生效

### ISSUE THREAD

**Issue by 751496032** [gurecn/YuyanIme#80]

**Comment by gurecn** [comment]
当前手写功能暂时到期还未恢复，我还在调研其他可行性替代方案。
暂时的结果看，可能短期内手写输入功能不会恢复了。
感谢您的反馈。

**Comment by iminto** [comment]
如果长期不可用的话，建议关闭手写输入法的显示。

**Comment by gurecn** [comment]
手写输入功能已经实现，期待您下载体验。
