### ISSUE TITLE
关于数字行和键盘布局的期许

### ISSUE THREAD

**Issue by leisure365** [gurecn/YuyanIme#81]
1、数字行虽然可以设置显示和隐藏，但数字行的高度是固定的，能否增加数字行的高度调整功能？

2、键盘布局可否增加几种同文的比较全的键盘布局？当然如果能像仓输入法那样在程序里自定义就更好了。
![01](https://github.com/user-attachments/assets/f4094921-3305-4f47-bb1d-d68c141be8e9)
![02](https://github.com/user-attachments/assets/9fffb11e-0216-454a-ae1e-54b806c21047)

**Comment by gurecn** [comment]
新版本数字行高度已优化，期待您下载更新体验。感谢您的反馈。
