### ISSUE TITLE
建议语燕后续也加入中文词语联想功能

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#82]
隔壁小企鹅这个功能叫预测，如图
![IMG_20240927_000651.jpg](https://github.com/user-attachments/assets/73527385-312b-4219-bdd6-3fdb63e8593a)

另外反馈一下，有一个亮色主题启用边框只对空格键和回车键有效，其它按键还是无框，如图
![IMG_20240927_002029.jpg](https://github.com/user-attachments/assets/779dd386-a704-4220-ae0f-aff922529254)

**Comment by gurecn** [comment]
收到，规划的有相关功能，后续我会加入进来。感谢您的使用和反馈。

**Comment by swh922** [comment]
> 收到，规划的有相关功能，后续我会加入进来。感谢您的使用和反馈。

感谢大佬，最新版已下载使用，语燕作为主力输入法，越来越完善了，再提个小建议，我发现乱序17键盘的一些上滑符号是英文符号，比如问号、括号和叹号，希望后面能调整一下，尽量换成中文符号，毕竟是中文键盘
另外，我经常使用繁体，“爲”的异体字“為”这个字在港台使用频率远胜前者，现在语燕还是打不出来

**Comment by gurecn** [comment]
收到，乱序17键盘符号和繁体字“为”的问题会在本周版本修复

**Comment by gurecn** [comment]
新版本已发布并合入该问题，请下载体验[v20241217.10](https://github.com/gurecn/YuyanIme/releases/tag/v20241217.10)
