### ISSUE TITLE
反馈一个顶栏快捷表情按钮的问题


### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#84]
更新版本后，我清除了数据，一开始我发现只要点击过符号后，下次从顶栏点击快捷表情按钮会进入常用标点符号界面，而非表情界面，如下图
![IMG_20240930_184758.jpg](https://github.com/user-attachments/assets/be6cfea5-9e41-41ff-a3ed-320224ae60a9)

后面我尝试输入了几次表情后，发现点击快捷表情按钮后，常用表情界面同时显示常用符号和常用表情，如下图
![IMG_20240930_234618.jpg](https://github.com/user-attachments/assets/abeffdbd-351b-4721-9938-2b4ff677e70d)

鉴于符号界面的常用符号已经有常用符号了（如下图），建议常用表情界面纯粹只显示常用表情，而非同时显示常用符号和常用表情，这样更符合它的界面属性
![Screenshot_20240930-235201_Alpha Launcher.png](https://github.com/user-attachments/assets/6ee39362-691a-4af0-80d0-e79987b0b2da)

**Comment by gurecn** [comment]
表情界面会继续优化，这个问题下个版本修复🤝🤝

**Comment by gurecn** [comment]
表情符号布局界面已经优化，邀请您下载体验，期待您的反馈。
