### ISSUE TITLE
反馈个问题和提个建议

### ISSUE THREAD

**Issue by huayese** [gurecn/YuyanIme#85]
问题：定制工具栏里减少图标 工具栏宽度没有自适应 表现为空了一个位置
建议：输入方式里是否有增加英文九键的安排？

**Comment by gurecn** [comment]
第一个问题能加一个截图看一下吗？
第二个建议已经在规划中，后续会加入九键英文键盘。
感谢您的反馈。

**Comment by huayese** [comment]
> 第一个问题能加一个截图看一下吗？ 第二个建议已经在规划中，后续会加入九键英文键盘。 感谢您的反馈。

![WechatIMG24](https://github.com/user-attachments/assets/85dc51ef-f326-4bc5-bbee-5963e183a88a)
如上图 默认配置 我选择定制工具栏 取消工具栏上面的表情输入 工具栏上的对应位置会空出来 继续取消其他的 对应的位置也是如此 位置没有自适应

**Comment by gurecn** [comment]
不是的，菜单栏布局是居右排列的，当菜单数量填充不满菜单栏时，左侧会留空。当数量超出时，支持滑动显示。
