### ISSUE TITLE
剪贴板里的文本过一段时间会自动删除是bug吗？👀

### ISSUE THREAD

**Issue by ZARD1434** [gurecn/YuyanIme#88]

**Comment by gurecn** [comment]
大概多久？是某一条删除了还是某一条之前的全部删除了？

**Comment by ZARD1434** [comment]
> 大概多久？是某一条删除了还是某一条之前的全部删除了？

平时我就感觉这个输入法会自动清理剪贴板，所以我昨天下午18：06分的时候特意在手机复制一串数字，今天中午起床的时候发现剪贴板被清理了。

（我现在又清除了一下应用数据，看看这次剪贴板还会不会出bug🐛）

![Screenshot_20241003-214036_设置小助手.png](https://github.com/user-attachments/assets/33b0f90c-f37d-4dd9-b4de-fb3173f76c16)

还有就是如果把Android14系统的手势导航栏隐藏掉的话，输入法的布局会偏低

**Comment by ZARD1434** [comment]
> 大概多久？是某一条删除了还是某一条之前的全部删除了？

![Screenshot_20241003-150957_设置小助手.png](https://github.com/user-attachments/assets/95d83b17-7042-449f-b66c-6eda67fcdcf2)

这个bug🐛我清除了应用数据之后还能复现😂应该是每隔24小时清除剪贴板

**Comment by gurecn** [comment]
还有就是如果把Android14系统的手势导航栏隐藏掉的话，输入法的布局会偏低
> 这个问题可以点击键盘左上角应用图标-键盘调节-点击下方移动图标上移键盘。

剪切板这个我也在尝试复现，我等24小时试试。

**Comment by gurecn** [comment]
剪贴板问题新版本已经修复，期待您下载体验，期待您的反馈。
