### ISSUE TITLE
横屏布局有问题

### ISSUE THREAD

**Issue by Soltus** [gurecn/YuyanIme#9]
![image](https://github.com/user-attachments/assets/7e94e113-7462-4ade-8c30-72886bbb6b09)

测试其他输入法是正常的

**Comment by gurecn** [comment]
当前在横屏模式会自动切换成悬浮键盘，使键盘布局和竖屏尽量保持一致。横屏时如果占满宽度，会导致可视区域太小，体验较差。  
产品后续规划有`横屏分栏键盘`功能，待该功能实现后，会在横屏时默认为分栏键盘 。

**Comment by Soltus** [comment]
竖屏也有问题
![图片](https://github.com/user-attachments/assets/2914441d-26b2-4485-85a2-7cbf090761eb)

**Comment by gurecn** [comment]
有复现方式没？

**Comment by Soltus** [comment]
可能和悬浮键盘有关,切换到悬浮键盘再关闭可以恢复正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月18日(周日) 凌晨2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gurecn/YuyanIme] 横屏布局有问题 (Issue #9)




 
有复现方式没？

**Comment by gurecn** [comment]
您这样说我明白了，当前他们边距是统一设置的，下周五版本修复该问题。

**Comment by gurecn** [comment]
以上问题在最新的[v4.3.3版本](https://github.com/gurecn/YuyanIme/releases/tag/v4.3.3)已经优化，邀请您体验，期待您的反馈。

**Comment by Soltus** [comment]
问题没有解决，现在切换到横屏状态下会激活悬浮键盘且无法关闭，而且仍然占用布局高度不是真的悬浮键盘，切换到竖屏后依旧异常而且仍然无法关闭悬浮键盘

**Comment by Soltus** [comment]
又测了几次，有时候横竖屏的悬浮键盘是正常的，但是横竖屏切换基本上都会异常，然后横屏非悬浮键盘的布局应该是还没支持？测的有点晕了
