### ISSUE TITLE
bug: 英文键盘输入

### ISSUE THREAD

**Issue by ghost** [gurecn/YuyanIme#93]
英文键盘 无法输入 非标准词库的 字
如 llm
如 hhhhhhhhh

**Comment by Ecalose** [comment]
不是bug，长按英文大写键将拼写模式切换成直输模式就行

**Comment by gurecn** [comment]
这个问题可能是应用升级后旧方案未清除导致的，解决方案为：雨燕输入法卸载重装；或者到系统设置-应用管理-选择雨燕输入法，清空雨燕输入法存储数据就可以了。
![Uploading IMG_20241010_205029.jpg…]()
