### ISSUE TITLE
反馈 卡顿 

### ISSUE THREAD

**Issue by propro66** [gurecn/YuyanIme#94]
有时候第一个选字点不动卡  还有游戏里咋不能放大 太小了键盘 手写期待早点恢复 小企鹅选择太少了 就希望有手写 词库觉的比小企鹅好

**Comment by gurecn** [comment]
收到反馈，这几个问题我需要排查一下。横屏键盘后面也会优化。

**Comment by gurecn** [comment]
新版本手写功能已经实现，候选词界面进行了优化。期待您的使用与反馈。
