### ISSUE TITLE
BUG反馈 版本20241012.18

### ISSUE THREAD

**Issue by jark006** [gurecn/YuyanIme#96]
在MT管理器/小米文件管理器里重命名文件时，跳出名称编辑窗口时，此时旧名称文字默认处于选中状态，但瞬间被新弹出的雨燕输入法删除了。

也测试了其他输入法，都状态正常，在弹出输入面板时没有删除行为。

**Comment by jark006** [comment]
尴尬了，想录屏记录一下，发现无法复现了

**Comment by gurecn** [comment]
我试了一下，没有复现出来，不过我发现小米 `重命名菜单`的位置和雨燕输入法删除键的位置高度一样，我怀疑是不是点击完重命名后不小心又误触了一次删除键？

**Comment by swh922** [comment]
> 我试了一下，没有复现出来，不过我发现小米 `重命名菜单`的位置和雨燕输入法删除键的位置高度一样，我怀疑是不是点击完重命名后不小心又误触了一次删除键？

这个bug我复现了，不仅仅是在mt管理器里面，任何文件或文件夹重命名都有这个bug，文件只删除后缀之前的文件名，文件夹是删除文件名，两种复现方式，具体操作如下：
①当默认键盘是中文键盘的时候，点击重命名→点击切换中/英键→自动删除文件名
②当默认键盘是英文键盘的时候，点击重命名→弹出中文键盘且自动删除文件名
以下是复现bug的gif动图：
![Video_20241014_114745_404.gif](https://github.com/user-attachments/assets/6c45914c-1b3a-4cc6-8174-a7e5e1dc3052)

**Comment by swh922** [comment]
> 我试了一下，没有复现出来，不过我发现小米 `重命名菜单`的位置和雨燕输入法删除键的位置高度一样，我怀疑是不是点击完重命名后不小心又误触了一次删除键？

这个bug我复现了，不仅仅是在mt管理器里面，任何文件或文件夹重命名都有这个bug，文件只删除后缀之前的文件名，文件夹是删除文件名，两种复现方式，具体操作如下：
①当默认键盘是中文键盘的时候，点击重命名→点击切换中/英键→自动删除文件名
②当默认键盘是英文键盘的时候，点击重命名→弹出中文键盘且自动删除文件名
以下是复现bug的gif动图：
![Video_20241014_120935_588.gif](https://github.com/user-attachments/assets/9b89b60a-1b86-4e31-b1cd-b9c8dd07fc3e)
