### ISSUE TITLE
定制栏剪切板按钮动画过程中出现图标重合，如图

### ISSUE THREAD

**Issue by swh922** [gurecn/YuyanIme#98]
![IMG_20241013_132808.jpg](https://github.com/user-attachments/assets/ee81bd2e-0150-4d5f-b4de-daf5565dd9af)

**Comment by gurecn** [comment]
有复现方式没？我试了几次没有复现

**Comment by swh922** [comment]
> 有复现方式没？我试了几次没有复现

每次点击剪切板按钮动画过程中都会出现短暂重叠，过程不到一秒，都来不及截图，我是录屏又慢放截图的，虽不影响使用，但观感不佳

**Comment by gurecn** [comment]
哦哦，我明白你的意思了。这个是安卓转换动画，下个版本我去掉这个动画就可以了。感谢您的使用。

**Comment by gurecn** [comment]
[v20241018.21版本](https://github.com/gurecn/YuyanIme/releases/tag/v20241018.21)已修复该问题，期待您下载体验。
