### ISSUE TITLE
能不能出不带桌面图标的？

### ISSUE THREAD

**Issue by xiechangan123** [gurecn/YuyanIme#99]
如题，安安静静的做个内置输入法。桌面有图标感觉不简洁

**Comment by gurecn** [comment]
您的意思是支持输入法桌面图标隐藏功能吗？这个功能后续我可以加入进来。
但需要注意的是，桌面图标隐藏功能不是所有手机都支持的，当前部分国产定制系统会在应用隐藏后默认显示为安卓小人图标，那样的话体验会差一些。

**Comment by xiechangan123** [comment]
> 您的意思是支持输入法桌面图标隐藏功能吗？这个功能后续我可以加入进来。 但需要注意的是，桌面图标隐藏功能不是所有手机都支持的，当前部分国产定制系统会在应用隐藏后默认显示为安卓小人图标，那样的话体验会差一些。

1、我是类原生，应该没问题；
2、我的本意是彻底去除桌面图标，而不是加个控制开关。。。去广告去图标搜狗输入法用习惯了，就想着雨燕也这样；
3、这只是我个人小需求，不是必须的。

**Comment by gurecn** [comment]
明白您的意思，我发现很多输入法，比如谷歌输入法，是支持隐藏输入法图标的，这个我后续加进来。
